consu_mapping = {
        'DATA':['DATA','data'],
        'CUSTOMERID': ['customerid','customernumber','cusid','idno','custid','customeridind','customerkey','custcode','subjectidentificationnumber','customerno', 'customersid', 'idno', 'otheridnumber', 'customernumber', 'custno', 'customerkey', 'subjectidentificationnumber', 'custcode', 'customerid', 'customeridorcustomernumber', 'subjectidno', 'subjectidentificationnumber', 'customersnumber', 'sheet1customerid', 'idno', 'consumerid'],
        'BRANCHCODE': ['branchcode','branchidno','brchcode','branch','customerbranchcode','customersbranchcode','branchid','branchidentificationnumber', 'branchidnumber','branchidentificationno'],
        'SURNAME': ['surname','Surname','surname','lastname', 'Surname', 'surname', 'fullname', 'mfassociationname', 'description', 'subfullname', 'fullname', 'subjectfullname', 'surnamefirstnameothernames', 'fullnames', 'acctname', 'name', "customersname", 'businessname', 'lastname', 'subjectfamilynamelastname', 'subjectfamilynamelastname', 'registeredname', 'customername', 'businessname', 'surname 11'],
        'FIRSTNAME': ['firstname','first', 'subjectfirstname'],
        'MIDDLENAME': ['middlename', 'othernames', 'middlenames','othername', 'subjectsmiddlename', 'subjectmiddlename'],
        'DATEOFBIRTH': ['dateofbirth','dateofloanfacilitydisbursement','dateofcommencement','birthofdate','datebirth','birthdate','dob','dateofincorporation', 'birthday', 'dateofbirthddmmyyyy', 'birthdateddmmyyyy', 'dob', 'birthdaymonthyear', 'birthday', 'birthdateyyyymmdd', 'dateofbirthyyyymmdd', 'dateofbirthyyyymmdd', 'birthdateddmmyyyy'],
        'NATIONALIDENTITYNUMBER': ['nationalidnumber','nationalidno','nin','nationalidentityno','nationalidentitynumber','nationalidentitynumber','nationalidcode','nationalid','natidcardnum','nationalidcode','nationalidnumber','subjectidentificationnumber','subjectnationalidentificationcode'],
        'DRIVERSLICENSENUMBER': ['driverslicence','driverlicence','driverlicense','driverslicense','driverslicenseno','driverlicenseno','driverslicenceno','driverlicenceno','driverslicensenumber','driverlicensenumber','driverslicencenumber','driverlicencenumber','DriversLicenseNo', 'driverslicenseno'],
        'BVNNUMBER': ['bvnno','bankverificationnumber','bankverificationnum','customerbvn','otheridnumber','bvn','bankbvn','bankverificationno'],
        'PASSPORTNUMBER' : ['passportno','passport no','passportnumber','passportno','passportnumber','passport','passportno','passportid','psprtnum','subjectinternationalpassport'],
        'PENCOMIDNUMBER': ['pencomidnumber','pencom id number','pencomid number','pencomidnumber', 'pencomid', 'pencomnumber', 'pensioncommissionnumber', 'pensionnumber', 'subjectpencomidnumber'],
        'OTHERID' : ['otherid','othersid','individualtaxidno','otheridnumber','otheridnum','otheridno'],
        'GENDER': ['gender','gender01','sex','subjectgender'],
        'NATIONALITY': ['nationality','subjectnationalitycountry','subjectnationalitycountry','nationalit','nationality', 'citizenship', 'subjectnationality'],
        'MARITALSTATUS': ['maritalstatus','custmaritalstatus','customermaritalstatus','marital'],
        'MOBILENUMBER': ['mobilephonenumbers','phone','mobilephonenumber','mobilephone','moblenumber','moblephone','mobilenumber','phonenumber', 'mobile','telephone', 'telephonenumber', 'contactnumber', 'subjectphone', 'tel', 'telno', 'subjecttellno', 'subjecttelno'],
        'PRIMARYADDRESSLINE1': ['primaryaddrline1','primaryadressLine1','primaryaddress1','primaryaddressline1','primaryaddressline1', 'address1','addressline1','address1line1','resdaddr1','addresstype1','address1','address','residentialaddress','addresstype1line1','primaryaddressline1','custpermaddr1','residentialaddressline1','primaryaddressline1','postaladdress1','businessofficeaddressline1','residentialaddressline1','addresstype1line1','primaryaddressline1','addresstype1','buslinetype1','businessofficeaddressline1','addresstype1line1','locationaddressline1','address', 'residentialaddress', 'homeaddress','subjectaddress', 'addr', 'location'],
        'PRIMARYADDRESSLINE2': ['primaryaddrline2','primaryaddressline2','addressline2','residentialaddress2','residentialaddress2','residentialaddress2','address2','addressline2','address1line2','addresstype1line2','primaryaddressline2','custpermaddr2','residentialaddressline2','primaryaddressline2','businessofficeaddressline2','residentialaddressline2','primaryaddressline2','buslinetype2','address2','addresstype1line2','locationaddressline2'],
        'PRIMARYADDRESSCITY': ['primaryaddresscity','primarycitylga','primarycitylga','addressline3','addresscity','residentialaddress3','residentialaddress3','address3','addressline3','address1city','addresstype1city','lga','addresstype1lgacity','primarycitylga','addresstype1lgacity','addresstype1citylga','localgovernmentoforigin','cityaddr','city'],
        'PRIMARYADDRESSSTATE': ['primaryaddressstate','primaryaddress','primarystate','addressstate','residentialaddress4','residentialaddress4','state','address1state','addresstype1state','primarystate','addresstype1state','stateoforigin','addresstype1citylga','stateaddr'],
        'PRIMARYADDRESSCOUNTRY': ['primaryaddresscountry','primarycountry','primarycountry','addresscountry','country','address1country','addresstype1country','primarycountry','custpermcntrycode','custcomucntrycode','addresstype1country','countaddr'],
        'PRIMARYADDRESSPOSTCODE':['primaryaddresspostcode','postalcdeofresaddr'],
        'EMPLOYMENTSTATUS': ['employmentstatus','employmentstat','empstatus'],
        'OCCUPATION': ['occupation','ocupation','natureofbusiness','employerdetail','occup'],
        'BUSINESSCATEGORY': ['businesscategory','businescategory','buscate','businesscat','buscat'],
        'BUSINESSSECTOR': ['businesssector','bussector','bussec','businesssec'],
        'BORROWERTYPE': ['borrowertype','borowtype'],
        'TAXID': ['taxid','individualtaxidno','individualtaxid','taxidno','individualtax'],
        'PICTUREFILEPATH': ['picturefilepath','picfile'],
        'EMAILADDRESS': ['emailaddress','email','emailadd','subjectemail', 'mail'],
        'EMPLOYERNAME': ['employername','employer','employerdetail','employerid'],
        'EMPLOYERADDRESSLINE1': ['employeraddrline1','employeraddress1','employeraddressline1','employeraddline1','emploeraddress1','employeraddress','employeraddress1','custempaddr1','empaddr1'],
        'EMPLOYERADDRESSLINE2': ['employeraddrline2','employeraddress2','employeraddressline2','employeraddline2','emploeraddress2','employeraddress2','employeraddress2','custempaddr2','empaddr2'],
        'EMPLOYERCITY': ['employerlgacity','employercity','emploeraddress3','employeraddress3','custempcitycode','empcity',],
        'EMPLOYERSTATE': ['employerstate','emploeraddress4','employerstate','custempstatecode','empstate','employersstate'],
        'EMPLOYERCOUNTRY': ['employercountry','custcomucntrycode1','empcountr','employercountry','employerscountry'],
        'TITLE': ['title','customertitle'],
        'PLACEOFBIRTH': ['placeofbirth','pob','birthplace','placebirth'],
        'WORKTELEPHONE': ['workphone','mobile','moilephone','worktelephone','databasephonenumber','phoneno','telephonenumber','cellulartelephone','hometelephone','phonenumber','phoneno','mobilephone','workphone','custcomuphonenum1','mobilenumber','telephone','worktelephone'],
        'HOMETELEPHONE': ['homephone','telephone','hometelephone','cellulartelno','homephone','custcomuphonenum2','phonenumber'],
        'SECONDARYADDRESSLINE1': ['secondaryaddressline1','postaladdress1','address2line1','residentialaddressline1','secaddr1','addresstype2line3'],
        'SECONDARYADDRESSLINE2': ['secondaryaddressline2','secondaryaddressline11','secondaryaddressline12','postaladdress','postaladdress2','address2line2','residentialaddressline2','secondaryaddressline2','secaddr2','addresstype2line2','secaddline2','secadd2'],
        'SECONDARYADDRESSCITYLGA': ['secondaryaddresscitylga','postaladdress3','address2city','seccity','addresstype2city','secaddcity','secaddcitylga','secaddlga','Secondary Address LGA/CITY'],
        'SECONDARYADDRESSSTATE': ['secondaryaddressstate','postaladdress4','address2state','secaddtate','secstate','addresstype2state'],
        'SECONDARYADDRESSCOUNTRY': ['secondaryaddresscountry','address2country','postaladdress3','secondaryaddresscountry','seccountr'],
        'SECONDARYADDRESSPOSTCODE': ['secondaryaddresspostcode','postalcdeofresaddr1','address2postcode','postaladdress'],
        'SPOUSESURNAME': ['spousesurname','spousessurname','spousessur','spousesur','spouseslastname','spouselastname'],
        'SPOUSEFIRSTNAME': ['spousesfirstname','spousefirstname','spousefir','spousefirst','spousef'],
        'SPOUSEMIDDLENAME': ['spousesmiddlename','spousemiddlename','spousesothername','spouseothername']
}

comm_mapping = {
        'DATA':['Data'],
        'BUSINESSREGISTRATIONNUMBER': ['businessidentificationnumber','businesidentificationnumber','businessid','businessidno','businessidentificationno','businessidentificationno','businessregistrationnumber','businesidentificationnumber','regno','regno','businessidno','rcnumber','busregnumber','businessregistrationnumber','businessregno','businessidentificationno','busregnum','businessregistrationnumber','subjectmicroenterpriseregistrationnumber','businessidentificationno','businessidentificationnumber','subjectbusinessregistrationnumber','trusteeregisteredno','refno','busregno','dob','businnessregno'],
        'BUSINESSNAME': ['businessname','businesname','surname','customername','surnamefirstnameothernames','fullname','mfassociationname','description','registeredname','surname1','subjectfamilynamelastname','subjectregisteredname','acctname','subjectmicroenterprisename','businessname1','subjectregisteredname','registeredname','subfullname','customername','businessregisteredname'],
        'BUSINESSTRADINGNAME':['BUSINESSTRADINGNAME','businesstradingname'],
        'BUSINESSCATEGORY': ['businesscategory','businescategory','businesscat','buscat','bizcat','natureofbusiness', 'corporatebizcategory', 'buscategory', 'businesstype111'],
        'BUSINESSSECTOR': ['bussinesssector','bussinessector','bussec','businesssec','industrysector','industrysector','businesscorporatetype','businesscorptype','businescorpotype','businesscorpotype','businescorporatetype','industrialsector','subjectsmicroenterprisemainbusinesslineoccupationtype','businesscorptype'],
        'DATEOFINCORPORATION': ['dateofincoporation','dateofincorporation','dateofincorpo','commencedate','dateofbirth','registrationdate','dateofincorp','dateofcommencement','birthdate','dateofincorporation','dateofcommencement','subjectmicroenterpriseregistrationdatebusinessregistration','dateofregistration','regdate','enterpriseregistrationdate','businessregdate'],
        'CUSTOMERID': ['customerid','customerno','customernumber','customerkey','subjectidentificationnumber','custcode','customerid','custid','customeridorcustomernumber','idno','customersnumber','custno','subjectidno','customeridcorp'],
        'CUSTOMERBRANCHCODE': ['customersbranchcode','branchcode','branchidno','brchcode','branch','customerbranchcode','branchid',  'branchidentificationnumber', 'dataproviderbranchidentificationnumber'],
        'BUSINESSOFFICEADDRESSLINE1': ['businessofficeaddressline1','businessaddress1','businessaddressline1','businessofficeaddressline1', 'primaryaddressline1', 'residentialaddress1', 'residentialaddress1', 'locationaddress1', 'businessofficeline1', 'address1', 'addressline1', 'locationaddr1', 'addresstype1', 'address1', 'locationaddressline1', 'residentialaddress', 'businessofficeaddress1', 'custcomuaddr1', 'residentialaddress1', 'addresstype1line1', 'locationaddressline1', 'businessoffice', 'address', 'address1line1', 'primaryaddressline1', 'primaryessline1addresstype1line1'],
        'BUSINESSOFFICEADDRESSLINE2': ['businessofficeaddressline2','businessaddress2','businessaddressline2', 'primaryaddressline2', 'residentialaddress2', 'locationaddressline2', 'locationaddress2', 'address2', 'addressline2', 'locationaddr2', 'addresstype2', 'businessofficeaddress2', 'custcomuaddr2', 'residentialaddressline2', 'residentialaddress2', 'businessofficeaddressline2', 'addresstype2line1', 'locationaddressline2', 'addresstype1line2', 'address1line2', 'primaryaddreessline2', 'addresstype1line2'],
        'BUSINESSOFFICEADDRESSCITYLGA': ['businesscitylga','businesscity','businessofficeaddresscitylga','citylga', 'bcitylga', 'addresstype1citylga', 'residentialaddress3', 'citylga', 'address1city', 'primarycitylga', 'city'],
        'BUSINESSOFFICEADDRESSSTATE': ['businessstate','businessofficeaddressstate','state','primarystate', 'locationaddress4', 'addresstype1state', 'addresstype2state', 'custcomustatecode', 'residentialaddress4', 'addresstype1state', 'address1state'],
        'BUSINESSOFFICEADDRESSCOUNTRY': ['businesscountry','businessofficeaddresscountry','country','primarycountry', 'custcomucntrycode', 'addresstype1country', 'address1country'],
        'BUSINESSOFFICEADDRESSPOSTCODE':['BUSINESSOFFICEADDRESSPOSTCODE','businessofficeaddresspostcode'],
        'EMAILADDRESS': ['emailaddress','emailid','email'],
        'SECONDARYADDRESSLINE1': ['secondaryaddress1','secondaryaddressline1', 'postaladdress1', 'postaladdressline1', 'postalcode1', 'secondaryaddressline1', 'custpermaddr1', 'secondaryaddressline1', 'marketassociationaddress', 'addresstype2line1'],
        'SECONDARYADDRESSLINE2': ['secondaryaddress2','secondaryaddressline2', 'secondaryaddressline11', 'postaladdress2', 'postaladdressline2', 'postalcode2', 'secondaryaddressline2', 'custpermaddr2', 'secondaryaddressline2', 'addresstype2line2'],
        'SECONDARYADDRESSCITYLGA': ['secondaryaddresscitylga','citylga1'],
        'SECONDARYADDRESSSTATE' : ['secondaryaddressstate','state1', 'secondaryaddressstate', 'postaladdressline4','postalcode4','custpermstatecode', 'state1', 'addresstype2state' ],
        'SECONDARYADDRESSCOUNTRY' : ['secondaryaddresscountry','country1', 'cust_perm_cntry_code','address2country','postaladdress3','secondaryaddresscountry','seccountr'],
        'SECONDARYADDRESSPOSTCODE' : ['secondaryaddresspostcode','postcode','postalcodeofresaddr', 'postalcodeofresidenceaddress', 'postalcode', 'addresstype1postalcode', 'addresstype2postalcode', 'postaladdress', 'postalcodeofresidentialaddress', 'addresstype1postalcode', 'address1postcode', 'addresstype1postal'],
        'TAXID' : ['taxid','taxidentificationno', 'taxidentificationnumber', 'taxidentificationnum'],
        'PRIMARYPHONENUMBER' : ['primaryphonenumber','cellulartelephone', 'telephonenumber', 'phoneno', 'telephonenumber', 'officetelephone2', 'cellulartelno', 'officetelephone1', 'telephoneareacode', 'hometelephone', 'custcomuphonenum1', 'businessphone', 'phonetelephonenumber'],
        'SECONDARYPHONENUMBER' : ['secondaryphoneno','secondaryphonenumber','worktelephone', 'officetelephone2','mobileno','mobilephonenumber','worktelno', 'phonenumber', 'telephonenumber',  'mobilephone', 'secondaryphonenumber', 'workphone', 'custcomuphonenum2']
    }
credit_mapping = {
        'CUSTOMERID': ['customerid','customernumber','cusid','idno','custid','customeridind','customerkey','custcode','subjectidentificationnumber','customerno', 'customersid', 'idno', 'otheridnumber', 'customernumber','custno', 'customerkey', 'customeridorcustomernumber', 'subjectidno','subjectidentificationnum','subjectidentificationno','sheet1customerid'],
        'ACCOUNTNUMBER': ['accountnumber','accountno',  'loanno', 'currentacct', 'microcreditfacilityaccountnumber', 'acctnumloanno', 'foracid', 'facilityaccountnumber', 'accountnumber', 'microcreditfacilityaccountnumber', 'loanid', 'code', 'acctno', 'accountnoaccountid','acno','accountnum','acctnum'],
        'ACCOUNTSTATUS': ['accountstatus','creditstatus', 'statuscode', 'loanstatus','accounttypecode', 'custstatcode','schmcode', 'status','actstatus','acctstaus','acctstatus'],
        'ACCOUNTSTATUSDATE': ['accountstatusdate', 'statusdte', 'statusdate', 'accountstatusdate', 'custstatchgdate', 'statusdat', 'accountstatusdate','actstadate','statusdat','dateopened','consentstartdate','statusdays','accstatusdate'],
        'LOANEFFECTIVEDATE': ['loaneffectivedate','dateofloandisbursement','Date of Loan disbursement','dateofloan','dateloandisbursedloaneffectivedate','dateofloanfacilitydisbursementloaneffectivedate','loaneffectivedate','dateofdisbursement','disbursementdate','dateaccountopened','dateopened','firstdisbdt','opendate','dateacctopenned','dateofmortgagefacilityapproval','effectdate','startdate','accountactivationfirstdisbursementdate','startdate','dteaccountopened','dateaccountopened','accountactivationfirstdisbursementdate','dateofdisbursement','acctopndate','effectivedate','loaneffectivedate','accountactivationfirstdisbursementdate','disbutiondate','dateofcreditfacilityapproval','approvaldatedateoffirstdisbursement','approvaldate','issdate','issuedate','tdate','facilityapprovaldate','firstdisburmentdate'],
        'DEFEREDPAYMENTDATE':['DEFEREDPAYMENTDATE','deferedpaymentdate'],
        'CREDITLIMIT': ['creditlimit','creditlimitfacilityamountgloballimit','facilityamount','globallimit','openbalfirstdisbursementamt','amountgranted','openbalancecreditlimit','openingbalance','sanctlim','loanamountorcreditlimitforoverdraftaccounts','creditlimitfacilityamountgloballimit','currentbalance','amountequity'],
        'AVAILEDLIMIT': ['availedlimit','facilityamount','facilityamt','availedlimited','loanamount','loanfacilityamount','loanamountavailedlimit','loanfacilityamountavailedlimit','amountdisbursed','amountgranted','openingbalance','openbalance','loanfacilityamountavailedlimit','loanfacilityamount','approvedamt','amountdisbursedtilldate','approvedamount','openingbalance','amountgrantedcreditcardlimit','loanamountavailedlimit','principal','approvedamount','loanamt','amountapproved','loanamtloanamt','loanfacilityamountavailedlimit'],
        'OUTSTANDINGBALANCE': ['outstandingbalance','accountbalance','openingbalance','currentbalance','accountbal','balcurr','currentbal','principaloutstandingamount','outstandingprincipal','clrbalamt','trandatebal','currentoutstandingbalance','currentoutstanding','accountbalancecreditbalance','balance','totaloutstanding','acctbalance'],
        'CURRENTBALANCEDEBITIND':['currentbalancedebitind'],
        'INSTALMENTAMOUNT': ['instalmentamount','installmentamount','installamtprincipal','instalmentamt','installmentamountprincipal','totalinstallmentamount','installmentamount','instalmentamountn','installmentalamountprincipalpaidsofar'],
        'CURRENCY': ['curency','currencycode','currency','currcode','currengncy'],
        'DAYSINARREARS': ['daysinarrears','daysoverdue','monthsinarrears','dpdinmonths','montharrears','monthsarrears','daysoverdue','numberofdaysoverduemicrocreditfacility','daysinarrears','daysinarrears','numberofdaysoverduemicrocreditfacility','noofdaysoverdue','numberofdaysoverdue','daysareas','overduedaysprin'],
        'OVERDUEAMOUNT': ['overdueamount','overdueamtprn','amountoverdue','amountoverduearrearsamount','overdue'],
        'FACILITYTYPE': ['product','loantype','loanfacilitytype','accounttype','facilitytype','type','accounttypecode','typeofaccount','mortgagefacilitytype','customercategory','loanfacilitytype','transactiontypecode','schmtype','creditfacilitytype'],
        'FACILITYTENOR': ['loantenor','loanfacilitytenormonths','loan tenor','loanfacilitytenor','term','loan facility tenor','facility tenor','facilitytenor','FACILITYTENOR','LOAN (FACILITY) TENOR','LOAN DURATION','LOAN DURATION DAYS','LOAN_DURATION','TENORINDAYS','LOAN FACILITY TENOR','LOANDURATION','TERM','LOAN TENOR','LOAN DURATION (DAYS)','FACILITY TENOR','LOAN_TENOR','TENOR'],
        'FACILITYOWNERSHIPTYPE':['FACILITYOWNERSHIPTYPE'],
        'REPAYMENTFREQUENCY': ['repaymentfrequency','repayment frequency','REPAYMENTFREQUENCY','REPAYMENT FREQUENCY','REPAY FREQUENCY','FREQUENCY','REPAYMENT_FREQUENCY','REPAY_FREQ','PRINCIPAL REPAYMENT FREQUENCY','INTERESTFREQTYPE','INSTALLMENT_FREQUENCY','LR_FREQ_TYPE','RPYM_FREQ'],
        'LASTPAYMENTDATE': ['lastpaymentdate','last payment date','LASTPAYMENTDATE','LAST PAYMENT DATE','LAST PAYMENT RECEIVED DATE','DATE LAST PYMT WAS RCVD','PAYMENT DATE','LATEST_PAYMENT_DATE','LAST_TRANSACTION_DATE','LAST_PAYMT_DT_PRN','LAST_PAYMENT','LASTINTERESTPAIDDATE','DATE LATEST PAYMENT RECEIVED','LASTREPAYMENTDTE','LASTREPAYMENTDATE','LAST_PAYMENT_DATE','LAST_TRAN_DATE','DATE ON WHICH LAST PAYMENT WAS RECEIVED','LAST_DATE','LAST_INT_REC_DATE','LAST_INSTALMENT_DATE','DATELASTPAYMENTRECEIVED'],
        'LASTPAYMENTAMOUNT': ['lastpayamount','lastpaymentamount','last payment amount','LASTPAYMENTAMOUNT','LAST PAYMENT AMOUNT','LAST AMOUNT PAID','LAST PAYMENT RECEIVED','LASTPAYMENT','LAST_AMOUNT_PAID','LAST_AMT_RECVD_PRN','LAST_AMOUNT_RECEIVED','LASTTOTALPAYMENT','LASTREPAYMENTRECEIVED','LAST_PAYMENT_AMOUNT','LAST PAY AMOUNT','LAST PAYMENT AMOUNT RECEIVED','INSTALLMENT AMOUNT','LAST AMT PAYED','LAST_PAY_AMOUNT','PRINCIPAL PAID','LAST_AMT','LASTAMOUNTPAID'],
        'MATURITYDATE': ['maturitydate','maturity date','MATURITYDATE','MATURITY DATE','PLANNED CLOSURE DATE','CLOSE MATURITY DATE','MATURITY_DATE','EXPIRY_DATE','MATURITY_DT','MATURITY','PLANNED CLOSURE/MATURITY DATE','TERMINALDATE','PLANNED CLOSURE/ MATURITY DATE','CLOSED/ MATURITY DATE','MATURITYDTE','EI_PERD_END_DATE','LIM_EXP_DATE','EXPIRY DATE OR MATURITY DATE OF FACILITY','MICRO CREDIT FACILITY ACCOUNT CLOSING DATE','MATURITY DATE1','END DATE','PLANNED FINAL REPAYMENT DATE','MATUARITY DATE','MAT DATE','EXPIRES','MATDATE'],
        'INCOME':['INCOME','income'],
        'INCOMEFREQUENCY':['INCOMEFREQUENCY'],
        'OWNERTENANT':['OWNERTENANT'],
        'NUMBEROFPARTICIPANTSINJOINTLOAN':['NUMBEROFPARTICIPANTSINJOINTLOAN'],
        'DEPENDANTS':['DEPENDANTS'],
        'LOANCLASSIFICATION': ['loanclassification','loan classification','LOANCLASSIFICATION','LOAN CLASSIFICATION','ASSET_CLASS','CLASSIFICATION','ASSET CLASSIFICATION (AC)','ASSET CLASSIFICATION','LOAN_CLASSIFICATION','ASSET_CLASSIFICATION','LOAN_CLASS','ASSETCLASSIFICATION'],
        'LEGALCHALLENGESTATUS': ['legalchallengestatus','legal challenge status','LEGALCHALLENGESTATUS','LEGAL CHALLENGE STATUS','LEGAL_CHALLENGE_STATUS','LEGAL_STAT'],
        'LITIGATIONDATE': ['litigationdate','litigation date','LITIGATIONDATE','LITIGATION_DATE','LITIGATION DATE','LITIG_DATE'],
        'CONSENTSTATUS': ['consentstatu','consentstatus','consent status','CONSENTSTATUS','CONSENT STATUS','CONSENT_STATUS','CONS_STAT'],
        'LOANSECURITYSTATUS': ['loansecuritystatus','loan security status','LOANSECURITYSTATUS','LOAN SECURITY STATUS','LOAN_SECURITY_STATUS','SECU_STAT'],
        'COLLATERALTYPE': ['collateraltype','collateral type','COLLATERALTYPE','COLLATERAL TYPE','COLLATERAL_TYPE','COLAT_TYPE'],
        'COLLATERALDETAILS': ['collateraldetails','collateral details','COLLATERALDETAILS','COLLATERAL INFORMATION','COLLATERAL DETAILS','COLLATERAL_DETAILS','COLAT_DET'],
        'PREVIOUSACCOUNTNUMBER': ['previousaccountnumber','previous account number','PREVIOUSACCOUNTNUMBER','PREVIOUS ACCOUNT NUMBER','PREVIOUS_ACCOUNT_NO','MICRO CREDIT FACILITY PREVIOUS ACCOUNT NUMBER'],
        'PREVIOUSNAME': ['previousname','previous name','PREVIOUSNAME','PREVIOUSNAMEPREVIOUS NAME','PREVIOUS_NAME','PREVIOUS NAME'],
        'PREVIOUSCUSTOMERID': ['previouscustomerid','previous customer id','previous customerid','PREVIOUSCUSTOMERID','PREVIOUSCUSTOMERIDPREVIOUS CUSTOMER ID','PREVIOUS_CUSTOMER_ID','PREVIOUS CUSTOMER ID','SUBJECT PREVIOUS IDENTIFICATION NUMBER','PREV ID NO'],
        'PREVIOUSBRANCHCODE': ['previousbranchcode','previous branchcode','previous branch code','PREVIOUSBRANCHCODE','PREVIOUSBRANCHCODEPREVIOUS_BRANCH_CODE','PREVIOUS BRANCH CODE','DATA PROVIDER PREVIOUS BRANCH IDENTIFICATION NUMBER'],

    }
prin_mapping = {
        'CUSTOMERID': ['customerid','customer id','customerno','customer no','CUSTOMERID','CUSTOMER ID','CONSUMERID','CUSTOMER_NO','CUSTOMER_NUMBER','CUSTOMER_KEY','SUBJECT IDENTIFICATION NUMBER','CUSTCODE','CUSTOMER_ID','CUST_ID','CUSTOMER ID (OR CUSTOMER NUMBER)','ID NO','CUSTOMERS NUMBER','CUST_NO','SUBJECT ID NO','CUSTOMERIDCORP'],
        'PRINCIPALOFFICER1SURNAME': ['surname','fullname','principal officer1 surname','principalofficer1surname','principal officer 1 surname','PRINCIPALOFFICER1SURNAME','PRINCIPAL OFFICER 1 SURNAME','DIRECTOR_1_SURNAME','GUANRANTORS NAME','GUARANTORSNAME','PRINCIPAL OFFICER1SURNAME','PRINCIPAL OFFICER SURNAME','OFFICER99'],
        'PRINCIPALOFFICER1FIRSTNAME': ['firstname','principalofficer1firstname','principal officer 1 firstname','principal officer1 firstname','PRINCIPALOFFICER1FIRSTNAME','PRINCIPAL OFFICER 1 FIRSTNAME','DIRECTOR_1_FIRST_NAME','PRINCIPAL OFFICER1FIRSTNAME','PRINCIPAL OFFICER FIRSTNAME'],
        'PRINCIPALOFFICER1MIDDLENAME': ['middlename','othernames','principalofficer1middlename','principal officer 1 middle name','principal officer1 middlename','principal officer 1 middlename','PRINCIPALOFFICER1MIDDLENAME','PRINCIPAL OFFICER 1 MIDDLENAME','DIRECTOR_1_OTHER_NAMES','PRINCIPAL OFFICER1MIDDLENAME','PRINCIPAL OFFICER MIDDLENAME'],
        'PRINCIPALOFFICER1DATEOFBIRTH': ['PRINCIPALOFFICER1DATEOFBIRTH','dob','d o b','principalofficer1dateofbirth','principal officer 1 date of birth','principal officer1 date of birth','dateofbirth','date of birth','P1DATE OF BIRTH','DIRECTOR_1_BIRTH_DATE','NATIONAL ID','PRINCIPAL DATE OF BIRTH','PRINCIPAL_OFFICER2_DATE_OF_BIRTH','DATE OF BIRTH','DOB'],
        'PRINCIPALOFFICER1GENDER': ['PRINCIPALOFFICER1GENDER','principal officer 1 gender','principal officer1 gender','principalofficer1gender','gender','P1GENDER','GENDER','PRINCIPAL_OFFICER2_GENDER','PRINCIPAL OFFICER GENDER'],
        'PRINCIPALOFFICER1PRIMARYADDRESSLINE1': ['principalofficer1primaryaddressline1','principal officer1 primary address line1','principal officer 1 primary address line 1', 'primaryaddressline1','PRINCIPALOFFICER1PRIMARYADDRESSLINE1','GUANRANTORS ADDRESS 1','GUARANTORSADDRESS','PRINCIPAL PRIMARY ADDRESS LINE 1','PRINCIPAL OFFICER PRIMARY ADDRESS LINE 1','P_PRIMARY ADDRESS LINE 1','PRINCIPAL_OFFICER2_ADDRESS_LINE1','PRINCIPAL OFFICER PRIMARY ADDRESS LINE1','Primary Address Line 1'],
        'PRINCIPALOFFICER1PRIMARYADDRESSLINE2': ['principalofficer1primaryaddressline2','principal officer1 primary address line2','principal officer 1 primary address line 2', 'primary address line2','primaryaddressline2','PRINCIPALOFFICER1PRIMARYADDRESSLINE2','PRIMARY ADDRESS LINE 2','GUANRANTORS ADDRESS 2','PRINCIPAL PRIMARY ADDRESS LINE 2','PRINCIPAL OFFICER PRIMARY ADDRESS LINE 2','P_PRIMARY ADDRESS LINE 2','PRINCIPAL_OFFICER2_ADDRESS_LINE2','PRINCIPAL OFFICER PRIMARY ADDRESS LINE2','Primary Address Line 2'],
        'PRINCIPALOFFICER1CITY': ['citylga','principal officer1 city lga','principalofficer1citylga','principal officer 1 city','principal officer1 city','principalofficer1city','PRINCIPALOFFICER1CITY','city','GUANRANTORS ADDRESS 3','P_CITY','PRINCIPAL_OFFICER2_CITY','PRINCIPAL OFFICER CITY','city'],
        'PRINCIPALOFFICER1STATE': ['principalofficer1state','principal officer 1 state','principal officer1 state','state','PRINCIPALOFFICER1STATE','P_STATE','PRINCIPAL_OFFICER2_STATE','PRINCIPAL OFFICER STATE','State'],
        'PRINCIPALOFFICER1COUNTRY': ['principal officer 1 country','principal officer1 country','principalofficer1country','country','PRINCIPALOFFICER1COUNTRY','P_COUNTRY','PRINCIPAL_OFFICER2_COUNTRY','PRINCIPAL OFFICER COUNTRY'],
        'PRINCIPALOFFICER1NATIONALID': ['principal officer 1 national id','principal officer1 national id','principalofficer1nationalid','national id','nationalid','PRINCIPALOFFICER1NATIONALID','NATIONAL ID','DIRECTOR_1_NATIONAL_ID_NUMBER','PRINCIPAL_OFFICER2_NATIONAL_ID','nationalidentitynumber'],
        'PRINCIPALOFFICER1DRIVERSLICENSENUMBER': ['principal officer 1 drivers license no','principal officer1 drivers license no','principalofficer1driverslicenseno','drivers license no','driverslicenseno','PRINCIPALOFFICER1DRIVERSLICENSENUMBER','DRIVERS LICENSE NO','Drivers License Number 1','DIR1_DRIVERS_LICE_NUMBER','PRINCIPAL_OFFICER2_DRIVERS_LICENSE_NO','PRINCIPAL OFFICER DRIVER\'S LICENSE','driverslicensenumber'],
        'PRINCIPALOFFICER1BVNNUMBER': ['principal officer1 bvnno','principal officer1 bvn no','principal officer 1 bvn no','principalofficer1bvnno','bvn no','bvnno','PRINCIPALOFFICER1BVNNUMBER','BVN NO','BVNNO'],
        'PRINCIPALOFFICER1PASSPORTNUMBER': ['principal officer 1 passport no','PASSPORTNUMBER','principal officer1 passport no','principalofficer1passportno','passport no','passportno','PRINCIPALOFFICER1PASSPORTNUMBER','PASSPORT NO','DIRECTOR_1_PASSPORT_NUMBER'],
        'PRINCIPALOFFICER1OTHERIDNUMBER':['principalofficer1otheridnumber','principal officer 1 other id number','principal officer1 other id number'],
        'PRINCIPALOFFICER1PHONENUMBER': ['principal officer 1 phone number','principal officer1 phone number','principalofficer1phonenumber','phoneno','phone no','phone number','phonenumber','PRINCIPALOFFICER1PHONENUMBER','phone no 1','phone no1','phoneno1','PHONE NO1','GUANRANTORS TELEPHONE NUMBER','GUARANTORSTELEPHONENUMBER','PRINCIPAL OFFICER PHONE NO1'],
        'PRINCIPALOFFICER1EMAILADDRESS': ['principal officer 1 email address','principal officer1 email address','principalofficer1emailaddress','email','email address','emailaddress','PRINCIPALOFFICER1EMAILADDRESS','PRINCIPALOFFICER1EMAILADDRESSE','MAIL ADDRESS1','email','e-mail'],
        'PRINCIPALOFFICER1POSITIONINBUSINESS': ['principal officer1 position in business','principalofficer1positioninbusiness','position in business','positioninbusiness','PRINCIPALOFFICER1POSITIONINBUSINESS','POSITION IN BUSINESS'],
        'PRINCIPALOFFICER2SURNAME': ['principalofficer2surname','principal officer 2 surname','principal officer2 surname','PRINCIPALOFFICER2SURNAME','PRINCIPAL OFFICER 2 SURNAME','DIRECTOR_2_SURNAME','surname','PRINCIPAL OFFICER2 SURNAME 2','surname1'],
        'PRINCIPALOFFICER2FIRSTNAME': ['principalofficer2firstname','principal officer 2 firstname','principal officer2 firstname','PRINCIPALOFFICER2FIRSTNAME','PRINCIPAL OFFICER 2 FIRSTNAME','DIRECTOR_2_FIRST_NAME','PRINCIPAL OFFICER2 FIRSTNAME 2','firstname','firstname2'],
        'PRINCIPALOFFICER2MIDDLENAME': ['principal officer 2middlename','principal officer 2 middle name','principal officer2 middlename','PRINCIPALOFFICER2MIDDLENAME','principalofficer2middlename','DIRECTOR_2_OTHER_NAMES','PRINCIPAL OFFICER2 MIDDLENAME 2','middlename','othername','PRINCIPAL OFFICER 2 MIDDLE NAME'],
        'PRINCIPALOFFICER2DATEOFBIRTH': ['dateofbirth1','d o b1','dob1','principal officer2 date of birth','principalofficer2dateofbirth','date of birth1','PRINCIPALOFFICER2DATEOFBIRTH','P2DATE OF BIRTH','DIRECTOR_2_BIRTH_DATE','PRINCIPAL OFFICER DATE OF BIRTH','P_DATE OF BIRTH','PRINCIPAL OFFICER2 DATE OF BIRTH 2','DOB','date of birth','dateofbirth2'],
        'PRINCIPALOFFICER2GENDER': ['principal officer2 gender','gender','principalofficer2gender1','principalofficer2gender1','gender1','gender 1','PRINCIPALOFFICER2GENDER','P2GENDER','GENDER','PRINCIPAL OFFICER2 GENDER','gender2'],
        'PRINCIPALOFFICER2PRIMARYADDRESSLINE1': ['principal officer2 primary address line1','principalofficer2primaryaddressline1','primaryaddressline12','primary address line2','primaryaddressline2','primaryaddressline11','PRINCIPALOFFICER2PRIMARYADDRESSLINE1','P2PRIMARY ADDRESS LINE 1','P_PRIMARY ADDRESS LINE 1','P_ PRIMARY ADDRESS LINE 1','PRINCIPAL OFFICER PRIMARY ADDRESS LINE 1','PRINCIPAL OFFICER2 PRIMARY ADDRESS LINE1','primaryaddress2line1','primary address 2 line1'],
        'PRINCIPALOFFICER2PRIMARYADDRESSLINE2': ['principalofficer2 primary address line21','principalofficer2primaryaddressline2','primaryaddressline13','primaryaddressline14','principalofficer2primaryaddressline21','primary address line21','primaryaddressline21','PRINCIPALOFFICER2PRIMARYADDRESSLINE2','P2PRIMARY ADDRESS LINE 2','P_PRIMARY ADDRESS LINE 2','P_ PRIMARY ADDRESS LINE 2','PRINCIPAL OFFICER PRIMARY ADDRESS LINE 2','PRINCIPAL OFFICER2 PRIMARY ADDRESS LINE2','primaryaddress2line2'],
        'PRINCIPALOFFICER2CITY': ['citylga1','city1','principal officer2 city lga','principalofficer2citylga', 'principal officer2 city','principalofficer2city','principalofficer2city1', 'city1', 'PRINCIPALOFFICER2CITY','P2CITY','P_CITY','CITY','PRINCIPAL OFFICER2 CITY','LGA'],
        'PRINCIPALOFFICER2STATE': ['state1','principal officer2 state','principal officer2 state1','principalofficer2state','principalofficer2state1','state 1','P2STATE', 'STATE1_2', 'STATE11', 'P_CITY','PRINCIPALOFFICER2STATE'],
        'PRINCIPALOFFICER2COUNTRY': ['country1','principal officer2 country','principalofficer2country','principal officer2 country1','principalofficer2country1','country','PRINCIPALOFFICER2COUNTRY','P2COUNTRY','P_COUNTRY','PRINCIPAL OFFICER2 COUNTRY','country2','country.1'],
        'PRINCIPALOFFICER2NATIONALID': [ 'nationalid1', 'principal officer2 national id','principalofficer2nationalid','principalofficer2nationalid1', 'nationalid2',  'national id1', 'PRINCIPALOFFICER2NATIONALID', 'P2NATIONAL ID','DIRECTOR_2_NATIONAL_ID_NUMBER','P_NATIONAL ID','NATIONAL ID', 'PRINCIPAL OFFICER2 NATIONAL ID'],
        'PRINCIPALOFFICER2DRIVERSLISCENCENUMBER': ['principal officer2 drivers license no','driversliscenceno','principalofficer2driverslicenseno','principalofficer2driverslicenseno1','driverslicenseno1','drivers license no1','PRINCIPALOFFICER2DRIVERSLISCENCENUMBER','Drivers License Number 2','P2DRIVERS LISCENCE NO','DIRECTOR_2_DRVS_LICENCE_NUMBER','DRIVERS LICENSE NO','PRINCIPAL OFFICER2 DRIVERS LICENSE NO','driverslicensenumber2'],
        'PRINCIPALOFFICER2BVNNUMBER': ['bvnno1','principal officer2 bvn no','principalofficer2bvnno','principalofficer2bvnno1','bvn no1','PRINCIPALOFFICER2BVNNUMBER','P2BVN NO','BVN NO','PRINCIPAL OFFICER2 BVNNO'],
        'PRINCIPALOFFICER2PASSPORTNUMBER': ['principal officer2 passport no','principalofficer2passportno','passport no1','passportno1','PRINCIPALOFFICER2PASSPORTNUMBER','P2PASSPORT NO','DIRECTOR_2_PASSPORT_NUMBER','PASSPORT NO','PRINCIPAL OFFICER2 PASSPORT NO'],
        'PRINCIPALOFFICER2OTHERIDNUMBER':['principalofficer2otheridnumber','principal officer 2 other id number','principal officer2 other id number'],
        'PRINCIPALOFFICER2PHONENUMBER': ['phoneno11','principal officer2 phone number','principal officer2 phonenumber','principalofficer2phonenumber','principal officer2 phone no','principalofficer2phoneno','phonenumber11','phone number1','phonenumber11','phoneno11','phoneno1','phone no11','phoneno 11','PRINCIPALOFFICER2PHONENUMBER', 'P2PHONE NO1', 'PHONE NO 2','P_PHONE NO1','PRINCIPAL OFFICER2 PHONE NO1'],
        'PRINCIPALOFFICER2EMAILADDRESS': ['PRINCIPALOFFICER2EMAILADDRESS','principalofficer2emailaddress','emailaddress1','email address1','emailaddress1','P2EMAIL ADDRESS','E-MAIL ADDRESS1','PRINCIPAL OFFICER2 E MAIL ADDRESS','email1'],
        'PRINCIPALOFFICER2POSITIONINBUSINESS': ['positioninbusiness1','principal officer2 position in business','principalofficer2positioninbusiness','principalofficer2positioninbusiness1','position in business1''PRINCIPALOFFICER2POSITIONINBUSINESS','P2POSITION IN BUSINESS','PRINCIPAL OFFICER2 POSITION IN BUSINESS','Position In Business 2']
    }
guar_mapping = {
        'CUSTOMERSACCOUNTNUMBER': ['customers account no','customers accountno','customersaccountno','CUSTOMERSACCOUNTNUMBER', 'CUSTOMERS ACCOUNT NO.', 'ACCOUNT_NO', 'MICRO CREDIT FACILITY  ACCOUNT NUMBER1','loanaccount'],
        'GUARANTEESTATUSOFLOAN': ['guaranteestatusofloan','guarantee status of loan','GUARANTEESTATUSOFLOAN', 'GUARANTEE STATUS OF LOAN'],
        'TYPEOFGUARANTEE': ['typeofguarantee','type of guarantee','TYPEOFGUARANTEE', 'TYPE OF GUARANTEE'],
        'NAMEOFCORPORATEGUARANTOR': ['nameofcorporateguarantor','name of corporate guarantor','NAMEOFCORPORATEGUARANTOR', 'NAMEOFCORPORATEGUARANTOR'],
        'BIZIDNUMBEROFCORPORATEGUARANTOR': ['bizidnumberofcorporateguarantor','biz id number of corporate guarantor','BIZ ID NUMBER OF CORPORATE GUARANTOR'],
        'INDIVIDUALGUARANTORSURNAME': ['guarantorssurname','individualguarantorssurname','individual guarantors surname','INDIVIDUALGUARANTORSURNAME', 'INDIVIDUAL GUARANTORS SURNAME', 'GUARANTOR NAME', 'GUANRANTORS NAME', 'GUANRANTORS NAME 1', 'GUARANTORSNAME', 'GUARANTOR DETAILS', "INDIVIDUAL GUARANTOR'S SURNAME", 'GUARANTOR_1 SURNAME','guarantorsurname','Guarantor Surname'],
        'INDIVIDUALGUARANTORFIRSTNAME': ['guarantorsfirstname','individualguarantorsfirstname','individual guarantors firstname','INDIVIDUALGUARANTORFIRSTNAME', 'INDIVIDUAL GUARANTORS FIRST NAME', 'GUANRANTORS NAME 2', "INDIVIDUAL GUARANTOR'S FIRST NAME", 'GUARANTOR_1 FIRST NAME', 'GUARANTOR_1 OTHER NAME','guarantorfirstname','Guarantor FirstName'],
        'INDIVIDUALGUARNTORMIDDLENAME': ['guarntorsmiddlename','guarntorsothernames','individualguarntorsmiddlename','individual guarntors middlename','INDIVIDUALGUARNTORMIDDLENAME', 'INDIVIDUAL GUARNTORS MIDDLE NAME', "INDIVIDUAL GUARNTOR'S MIDDLE NAME", 'GUARANTOR_1 NATIONAL ID NUMBER','guarantormiddlename'],
        'GUARANTORDATEOFBIRTHINCORPORATION': ['birthday','birthdate','dateofincorporation','dateofbirth','guarantorsdateofbirth','guarantorsdateofbirthincorporation','guarantors date of birth incorporation','GUARANTORDATEOFBIRTHINCORPORATION', 'GUARANTORS DATE OF BIRTH/INCORPORATION', 'GUARANTORSADDRESS', "GUARANTOR'S DATE OF BIRTH/INCORPORATION"],
        'GUARANTORGENDER': ['guarantorsgender','guarantors gender','GUARANTORGENDER', 'GUARANTORS GENDER', "GUARANTOR'S GENDER"],
        'GUARANTORNATIONALIDNUMBER': ['guarantorsnationalid','guarantors national id','guarantors nationalid','GUARANTORNATIONALIDNUMBER', 'GUARANTORS NATIONAL ID', "GUARANTOR'S NATIONAL ID", "Guarantor's National ID",'Guarantor National Identity Number'],
        'GUARNATORINTLPASSPORTNUMBER': ['guarantorsintlpassportnumber','guarantors intl passport number','GUARNATORINTLPASSPORTNUMBER', 'GUARNATORS INTL PASSPORT NUMBER', "GUARANTOR'S INTL PASSPORT NUMBER", 'GUARANTOR_1 PASSPORT NUMBER'],
        'GUARANTORDRIVERSLICENCENUMBER': ['guarantorsdriverslicencenumber','guarantors drivers licencenumber','guarantors drivers licence number','GUARANTORDRIVERSLICENCENUMBER', 'GUARANTORS DRIVERS LICENCE NUMBER', "GUARANTOR'S DRIVERS LICENCE NUMBER", "GUARANTOR_1 DRIVER’S LICENCE NUMBER"],
        'GUARANTORBVN': ['guarantorsbvn','guarantors bvn','GUARANTORBVN', 'GUARANTORS BVN', "GUARANTOR'S BVN"],
        'GUARANTOROTHERID': ['guarantorsotherid','guarantors otherid','guarantors other id','GUARANTOROTHERID', 'GUARANTORS OTHER ID', "GUARANTOR'S OTHER ID", 'GUARANTOR_1 OTHER ID NUMBER'],
        'GUARANTORPRIMARYADDRESSLINE1': ['guarantorsprimaryaddressline1','guarantors primary address line 1','guarantors primary address line1','GUARANTORPRIMARYADDRESSLINE1', 'GUARANTORS PRIMARY ADDRESS LINE 1', 'GUARANTORS ADDRESS LINE 1', 'GUANRANTORS ADDRESS LINE 2', 'GUARANTOR ADDY 1', 'GUANRANTORS ADDRESS 1', "GUARANTOR'S PRIMARY ADDRESS LINE 1", 'GUARANTOR_1 ADDRESS LINE1'],
        'GUARANTORPRIMARYADDRESSLINE2': ['guarantorsprimaryaddressline2','guarantors primary address line 2','guarantors primary address line2','GUARANTORPRIMARYADDRESSLINE2', 'GUARANTORS PRIMARY ADDRESS LINE 2', 'GUARANTORS ADDRESS LINE 2', 'GUANRANTORS ADDRESS LINE 21', 'GUARANTOR ADDY 2', 'GUANRANTORS ADDRESS 2', "GUARANTOR'S PRIMARY ADDRESS LINE 2", 'GUARANTOR_1 ADDRESS LINE2'],
        'GUARANTORPRIMARYADDRESSCITYLGA': ['guarantorsprimaryaddresscitylga','guarantors primary address city lga','guarantors primary address citylga','GUARANTORPRIMARYADDRESSCITYLGA', 'GUARANTORS PRIMARY ADDRESS CITY/LGA', 'GUARANTORS ADDRESS LINE 3', 'GUANRANTORS ADDRESS LINE 3', 'GUARANTOR ADDY 3', 'GUANRANTORS ADDRESS 3', "GUARANTOR'S PRIMARY ADDRESS CITY/LGA", 'GUARANTOR_1 ADDRESS LINE3'],
        'GUARANTORPRIMARYADDRESSSTATE': ['guarantorsprimarystate','guarantors primarystate','guarantors primary state','GUARANTORPRIMARYADDRESSSTATE', 'GUARANTORS PRIMARY STATE', "GUARANTOR'S PRIMARY STATE",'GUARANTORSTATE'],
        'GUARANTORPRIMARYADDRESSCOUNTRY': ['guarantorscountry','guarantorsprimarycountry','guarantors primary country','GUARANTORPRIMARYADDRESSCOUNTRY', 'GUARANTORS PRIMARY COUNTRY', "GUARANTOR'S PRIMARY COUNTRY"],
        'GUARANTORPRIMARYPHONENUMBER': ['guarantorsprimaryphonenumber','guarantors primary phonenumber','guarantors primary phone number','GUARANTORPRIMARYPHONENUMBER', 'GUARANTORS PRIMARY PHONE NUMBER', 'GUARANTORS TELEPHONE NUMBER', 'GUANRANTORS TELEPHONE NUMBER', 'GUARANTOR PHONE', 'GUARANTORSTELEPHONENUMBER', "GUARANTOR'S PRIMARY PHONE NUMBER"],
        'GUARANTOREMAIL': ['guarantorsemailaddress','guarantors email','guarantorsemail','guarantors email address','GUARANTOREMAIL', 'GUARANTORS E-MAIL ADDRESS', "GUARANTOR'S EMAIL ADDRESS"],
        'FILLER':['FILLER','filler']
    }


Gender_dict = {"Male":[ "Male", "male","M", "m",'001','01','1','mal'],
               "Female":["female",'002',"f",'02','2','femal']}
Country_dict = {'Nigeria':['ng', 'nigerian','nigeria','naija','ngr','ngn'],
                    "Andorra": ["andorra", "ad"],
                    "United Arab Emirates": ["united arab emirates", "uae","ae"],
                    "Afghanistan": ["afghanistan", "AF"],
                    "Antigua and Barbuda": ["antigua and barbuda", "ag"],
                    "Anguilla": ["anguilla", "ai"],
                    "Albania": ["albania", "al"],
                    "Armenia": ["armenia", "am"],
                    "Netherlands Antilles": ["netherlands antilles", "an"],
                    "Angola": ["angola", "ao"],
                    "Antarctica": ["antarctica", "aq"],
                    "Argentina": ["argentina", "ar"],
                    "American Samoa": ["american samoa", "as"],
                    "Austria": ["austria", "at"],
                    "Australia": ["australia", "au"],
                    "Aruba": ["aruba", "aw"],
                    "Åland Islands": ["aland Islands", "ax"],
                    "Azerbaijan": ["azerbaijan", "az"],
                    "Bosnia and Herzegovina": ["bosnia and herzegovina", "ba"],
                    "Barbados": ["barbados", "bb"],
                    "Bangladesh": ["bangladesh", "bd"],
                    "Belgium": ["belgium", "be"],
                    "Burkina Faso": ["burkina faso", "bf"],
                    "Bulgaria": ["bulgaria", "bg"],
                    "Bahrain": ["Bahrain", "bh"],
                    "Burundi": ["burundi", "bi"],
                    "Benin": ["benin", "bj"],
                    "Saint Barthélemy": ["saint barthélemy", "bl"],
                    "Bermuda": ["Bermuda", "BM"],
                    "Brunei Darussalam": ["brunei darussalam", "bn"],
                    "Bolivia": ["bolivia", "bo"],
                    "Brazil": ["brazil", "br"],
                    "Bahamas": ["bahamas", "bs"],
                    "Bhutan": ["bhutan", "bt"],
                    "Bouvet Island": ["bouvet island", "bv"],
                    "Botswana": ["botswana", "bw"],
                    "Belarus": ["belarus", "by"],
                    "Belize": ["belize", "bz"],
                    "Canada": ["canada", "ca"],
                    "Cocos (Keeling) Islands": ["cocos keeling islands", "cc"],
                    "Congo, The Democratic Republic of The": ["congo the democratic republic of the", "cd"],
                    "Zaire": ["congo the democratic republic of the", "cd"],
                    "Central African Republic": ["central african republic", "cf"],
                    "Congo": ["congo", "cg"],
                    "Switzerland": ["switzerland", "ch"],
                    "Côte d'Ivoire": ["côte divoire", "ci"],
                    "Cook islands": ["cook islands", "ck"],
                    "Chile": ["chile", "cl"],
                    "Cameroon": ["cameroon", "cm"],
                    "China": ["china", "cn"],
                    "Colombia": ["colombia", "co"],
                    "Costa Rica": ["costa rica", "cr"],
                    "Cuba": ["cuba", "cu"],
                    "Cape Verde": ["cape verde", "cv"],
                    "Christmas Island": ["christmas island", "cx"],
                    "Cyprus": ["cyprus", "cy"],
                    "Czech Republic": ["czech republic", "cz"],
                    "Germany": ["germany", "de"],
                    "Djibouti": ["djibouti", "dj"],
                    "Denmark": ["denmark", "dk"],
                    "Dominica": ["dominica", "dm"],
                    "Dominican Republic": ["dominican republic", "do"],
                    "Algeria": ["algeria", "dz"],
                    "Ecuador": ["ecuador", "ec"],
                    "Estonia": ["estonia", "ee"],
                    "Egypt": ["egypt", "eg"],
                    "Western Sahara": ["western sahara", "eh"],
                    "Eritrea": ["eritrea", "er"],
                    "Spain": ["spain", "es"],
                    "Ethiopia": ["ethiopia", "et"],
                    "Finland": ["finland", "fi"],
                    "Fiji": ["fiji", "FJ"],
                    "Falkland Islands (Malvinas)": ["falkland islands Malvinas", "fk"],
                    "Micronesia, Federated States of": ["micronesia, federated states of", "fm"],
                    "Faroe Islands": ["faroe islands", "fo"],
                    "France": ["france", "fr"],
                    "Gabon": ["gabon", "ga"],
                    "United Kingdom": ["united kingdom", "gb"],
                    "Grenada": ["grenada", "gd"],
                    "Georgia": ["Georgia", "ge"],
                    "French Guiana": ["french guiana", "gf"],
                    "Guernsey": ["guernsey", "gg"],
                    "Ghana": ["ghana", "gh"],
                    "Gibraltar": ["gibraltar", "gi"],
                    "Greenland": ["greenland", "gl"],
                    "Gambia": ["gambia", "gm"],
                    "Guinea": ["guinea", "gn"],
                    "Guadeloupe": ["guadeloupe", "gp"],
                    "Equatorial Guinea": ["equatorial guinea", "gq"],
                    "Greece": ["greece", "gr"],
                    "South Georgia and the south sandwich islands": ["south georgia and the south sandwich islands", "gs"],
                    "Guatemala": ["guatemala", "gt"],
                    "Guam": ["guam", "gu"],
                    "Guinea-Bissau": ["guineabissau", "gw"],
                    "Guyana": ["guyana", "gy"],
                    "Hong Kong": ["hong kong", "hk"],
                    "Heard Island and McDonald Islands": ["heard island and mcdonald islands", "hm"],
                    "Honduras": ["honduras", "hn"],
                    "Croatia": ["croatia", "hr"],
                    "Haiti": ["haiti", "ht"],
                    "Hungary": ["hungary", "hu"],
                    "Indonesia": ["indonesia", "id"],
                    "Ireland": ["ireland", "ie"],
                    "Israel": ["israel", "il"],
                    "Isle of Man": ["isle of man", "im"],
                    "India": ["india", "in"],
                    "British Indian Ocean Territory": ["british indian ocean territory", "io"],
                    "Iraq": ["iraq", "iq"],
                    "Iran, Islamic Republic of": ["iran islamic republic of", "ir"],
                    "Iceland": ["iceland", "is"],
                    "Italy": ["italy", "it"],
                    "Jersey": ["jersey", "je"],
                    "Jamaica": ["jamaica", "jm"],
                    "Jordan": ["jordan", "jo"],
                    "Japan": ["japan", "jp"],
                    "Kenya": ["kenya", "ke"],
                    "Kyrgyzstan": ["kyrgyzstan", "kg"],
                    "Cambodia": ["cambodia", "kh"],
                    "Kiribati": ["kiribati", "ki"],
                    "Comoros": ["comoros", "km"],
                    "Saint Kitts and Nevis": ["saint kitts and nevis", "kn"],
                    "Korea, Democratic People's Republic of": ["korea democratic peoples republic of", "kp"],
                    "Korea, Republic of": ["korea republic of", "kr"],
                    "Kuwait": ["kuwait", "kw"],
                    "Cayman Islands": ["cayman islands", "ky"],
                    "Kazakhstan": ["kazakhstan", "kz"],
                    "Lao People's Democratic Republic": ["lao peoples democratic republic", "la"],
                    "Lebanon": ["lebanon", "lb"],
                    "Saint Lucia": ["saint lucia", "lc"],
                    "Liechtenstein": ["liechtenstein", "li"],
                    "Sri Lanka": ["sri lanka", "lk"],
                    "Liberia": ["liberia", "lr"],
                    "Lesotho": ["lesotho", "ls"],
                    "Lithuania": ["lithuania", "lt"],
                    "Luxembourg": ["luxembourg", "lu"],
                    "Latvia": ["latvia", "lv"],
                    "Libyan Arab Jamahiriya": ["libyan arab jamahiriya", "ly"],
                    "Morocco": ["morocco", "ma"],
                    "Monaco": ["monaco", "mc"],
                    "Moldova, Republic of": ["moldova republic of", "md"],
                    "Montenegro": ["montenegro", "me"],
                    "Saint Martin": ["saint martin", "mf"],
                    "Madagascar": ["madagascar", "mg"],
                    "Marshall islands": ["marshall islands", "mh"],
                    "Macedonia, the former Yugoslav Republic of": ["macedonia the former yugoslav republic of", "mk"],
                    "Mali": ["mali", "ml"],
                    "Myanmar": ["myanmar", "mm"],
                    "Mongolia": ["mongolia", "mn"],
                    "Macao": ["macao", "mo"],
                    "Northern Mariana Islands": ["northern mariana islands", "mp"],
                    "Martinique": ["martinique", "mq"],
                    "Mauritania": ["mauritania", "mr"],
                    "Montserrat": ["montserrat", "ms"],
                    "Malta": ["malta", "mt"],
                    "Mauritius": ["mauritius", "mu"],
                    "Maldives": ["maldives", "mv"],
                    "Malawi": ["malawi", "mw"],
                    "Mexico": ["mexico", "mx"],
                    "Malaysia": ["malaysia", "my"],
                    "Mozambique": ["mozambique", "mz"],
                    "Namibia": ["namibia", "na"],
                    "New Caledonia": ["new caledonia", "nc"],
                    "Niger": ["niger", "ne"],
                    "Norfolk Island": ["norfolk island", "nf"],
                    "Nicaragua": ["nicaragua", "ni"],
                    "Netherlands": ["netherlands", "nl"],
                    "Norway": ["norway", "no"],
                    "Nepal": ["nepal", "np"],
                    "Nauru": ["nauru", "nr"],
                    "Niue": ["niue", "nu"],
                    "New Zealand": ["new zealand", "nz"],
                    "Oman": ["oman", "om"],
                    "Panama": ["panama", "pa"],
                    "Peru": ["peru", "pe"],
                    "French Polynesia": ["french polynesia", "pf"],
                    "Papua New Guinea": ["papua new guinea", "pg"],
                    "Philippines": ["philippines", "ph"],
                    "Pakistan": ["pakistan", "pk"],
                    "Poland": ["poland", "pl"],
                    "Saint Pierre and Miquelon": ["saint pierre and miquelon", "pm"],
                    "Pitcairn": ["pitcairn", "pn"],
                    "Puerto Rico": ["puerto rico", "pr"],
                    "Palestinian Territory, occupied": ["palestinian territory, occupied", "ps"],
                    "Portugal": ["portugal", "pt"],
                    "Palau": ["palau", "pw"],
                    "Paraguay": ["paraguay", "py"],
                    "Qatar": ["qatar", "qa"],
                    "Réunion": ["réunion", "re"],
                    "Romania": ["romania", "ro"],
                    "Serbia": ["serbia", "rs"],
                    "Russian Federation": ["russian federation", "ru"],
                    "Rwanda": ["rwanda", "rw"],
                    "Saudi Arabia": ["saudi arabia", "sa"],
                    "Solomon islands": ["solomon islands", "sb"],
                    "Seychelles": ["seychelles", "sc"],
                    "Sudan": ["sudan", "sd"],
                    "Sweden": ["sweden", "se"],
                    "Singapore": ["singapore", "sg"],
                    "Saint Helena": ["saint helena", "sh"],
                    "Slovenia": ["slovenia", "si"],
                    "Svalbard and Jan Mayen": ["svalbard and jan mayen", "sj"],
                    "Slovakia": ["slovakia", "sk"],
                    "Sierra Leone": ["sierra leone", "sl"],
                    "San Marino": ["san marino", "sm"],
                    "Senegal": ["senegal", "sn"],
                    "Somalia": ["somalia", "so"],
                    "Suriname": ["suriname", "sr"],
                    "Sao Tome and Principe": ["são tome and príncipe", "st"],
                    "El Salvador": ["el salvador", "sv"],
                    "Syrian Arab Republic": ["syrian arab republic", "sy"],
                    "Swaziland": ["swaziland", "sz"],
                    "Turks and Caicos islands": ["turks and caicos islands", "tc"],
                    "Chad": ["chad", "td"],
                    "French Southern Territories": ["french southern territories", "tf"],
                    "Togo": ["togo", "tg"],
                    "Thailand": ["thailand", "th"],
                    "Tajikistan": ["tajikistan", "tj"],
                    "Tokelau": ["tokelau", "tk"],
                    "Timor-Leste": ["timor-leste", "tl"],
                    "Turkmenistan": ["turkmenistan", "tm"],
                    "Tunisia": ["tunisia", "tn"],
                    "Tonga": ["tonga", "to"],
                    "Turkey": ["turkey", "tr"],
                    "Trinidad and Tobago": ["trinidad and tobago", "tt"],
                    "Tuvalu": ["tuvalu", "tv"],
                    "Taiwan, Province of China": ["taiwan, province of china", "tw"],
                    "Tanzania, United Republic of": ["tanzania, united republic of", "tz"],
                    "Ukraine": ["ukraine", "ua"],
                    "Uganda": ["uganda", "ug"],
                    "United States minor Outlying Islands": ["united states minor outlying islands", "um"],
                    "United States of America": ["united states of america", "us",'usa'],
                    "Uruguay": ["uruguay", "uy"],
                    "Uzbekistan": ["uzbekistan", "uz"],
                    "Holy see (Vatican City state)": ["holy see vatican city state", "va"],
                    "Saint Vincent and the Grenadines": ["saint vincent and the grenadines", "vc"],
                    "Venezuela": ["venezuela", "ve"],
                    "Virgin Islands, British": ["virgin islands, british", "vg"],
                    "Virgin Islands, U.S.": ["virgin Islands us", "vi"],
                    "Viet Nam": ["viet nam", "vn"],
                    "Vanuatu": ["vanuatu", "vu"],
                    "Wallis and Futuna": ["wallis and futuna", "wf"],
                    "Samoa": ["samoa", "ws"],
                    "Yemen": ["yemen", "ye"],
                    "Mayotte": ["mayotte", "yt"],
                    "South Africa": ["south africa", "za"],
                    "Zambia": ["zambia", "zm"],
                    "Zimbabwe": ["zimbabwe", "zw"]}

state_dict = {'Abia': ['abia', 'abia state','1','01','001'],
              'Adamawa': ['Adamawa','adamawa state','2','02','002' ],
              'Akwa-Ibom': ['akwaibom state', 'akwaibom', '3','03','003'],
              'Anambra': ['anambra', 'anambra State','4','04', '004'],
              'Bauchi': ['bauchi', 'bauchi state', '5','05', '005'],
              'Bayelsa': ['bayelsa','bayelsa state', '6','06','006'],
              'Benue': ['benue','benue state','7','07', '007'],
              'Borno': ['borno','borno State', '8','08','008'],
              'Cross river': ['crossriver','crossriver state',  '9','09','009'],
              'Delta': ['delta', 'delta state', '10','010'],
              'Ebonyi': ['ebonyi','ebonyi state','11', '011'],
              'Edo': ['edo','edo state', '12','012'],
              'Ekiti': ['ekiti','ekiti state', '13','013'],
              'Enugu': ['enugu','enugu state','14', '014'],
              'Federal Capital Territory': [ 'federal capital territory', 'fct', '15','015'],
              'Gombe': ['gombe','gombe state','16', '016'],
              'Imo': ['imo','imo state','17', '017'],
              'Jigawa': ['jigawa','jigawa state','18', '018'],
              'Kaduna': [ 'kaduna', 'kaduna state', '19','019'],
              'Kano': ['kano', 'kano state', '20','020'],
              'Katsina': ['katsina','katsina state','21', '021'],
              'Kebbi': ['kebbi','kebbi state','22', '022'],
              'Kogi': ['kogi','kogi state','23', '023'],
              'Kwara': ['kwara', 'kwara state','24', '024'],
              'Lagos': ['lagos', 'lagos state', '25','025'],
              'Nasarawa': ['nasarawa','nasarawa state','26', '026'],
              'Niger': ['niger','niger state', '27','027'],
              'Ogun': ['ogun','ogun state','28', '028'],
              'Ondo': ['ondo','ondo state', '29','029'],
              'Osun': ['osun','osun state','30', '030'],
              'Oyo': ['oyo','oyo state', '31','031'],
              'Plateau': ['plateau','plateau state','32', '032'],
              'Rivers': ['rivers','rivers state', '33','033'],
              'Sokoto': ['sokoto','sokoto state','34', '034'],
              'Taraba': ['taraba', 'taraba state', '35','035'],
              'Yobe': ['yobe','yobe state', '36','036'],
              'Zamfara': ['zamfara','zamfara state', '37','037']
             }
Marital_dict = {
    'Married': ['m', 'married', 'marry'],
    'Single': ['single', 's'],
    'Widower': ['wr', 'widower'],
    'Widow': ['wd', 'widow'],
    'Divorced': ['d', 'divorced']
}
Borrower_dict = {
    'Individual': ['individual', 'i'],
    'Joint': ['joint', 'j'],
    'Group': ['group', 'g']
}
Employer_dict = {
    'Unemployed': ['unemployed', 'ue'],
    'Employed': ['employed', 'e'],
    'Self-employed': ['selfemployed', 'self employed', 'se']
}
Title_dict = {
    'Mister': ['mr', 'mister'],
    'Mrs': ['mrs'],
    'Miss/Mrs': ['ms', 'missmrs'],
    'Miss': ['miss'],
    'Captain': ['captain', 'capt'],
    'Colonel': ['colonel', 'col'],
    'Doctor': ['doctor', 'dr', 'doc'],
    'Lady': ['lady'],
    'Lieutenant': ['lieutenant', 'lt'],
    'Major': ['major', 'maj'],
    'Pastor': ['pastor', 'pst', 'ps'],
    'Professor': ['professor', 'prof'],
    'Reverend': ['reverend', 'rev'],
    'Sergeant': ['sergeant', 'sgt'],
    'Sir': ['sir'],
    'His Excellency': ['he', 'his excellency'],
    'Justice': ['justice', 'judg'],
    'Chief': ['chief', 'chf'],
    'Alhaji': ['alhaji', 'alhj'],
    'Apostle': ['apostle', 'apos'],
    'Commander': ['commander', 'cdr'],
    'Bishop': ['bishop', 'bish'],
    'Flight Lieutenant': ['flight lieutenant', 'flt'],
    'Barrister (Lawyer)': ['barrister lawyer', 'barr'],
    'Major General': ['major general', 'mgen'],
    'General': ['general', 'gen'],
    'Honourable': ['honourable', 'hon'],
    'Engineer': ['engineer', 'engr']
}
Occu_dict = {"Agriculture": ["3000", "agriculture"],
             "Food Crops (Grains) – Distribution": ["3001", "food crops (grains) – distribution"],
             "Forestry": ["3002", "forestry"],
             "Fishing": ["3003", "fishing"],
             "Agricultural – Others": ["3004", "agriculturalothers"],
             "Food Crops (Grains) – Production": ["3005", "foodcropsgrainsproduction"],
             "Food Crops (Other) e.g. Tuber, Citrus": ["3006", "foodcropsotheregtubercitrus"],
             "Cash Crops (Cotton, cocoa, Palm Produce, Groundnuts, Oil Seeds, Rubber, Tobacco)": ["3007", "cashcropscottoncocoapalmproducegroundnutsoilseedsrubbertobacco"],
             "Poultry": ["3008", "poultry"],
             "Other Livestock": ["3009", "otherlivestock"],
             "Food Crops (Grains)": ["3010", "foodcropsgrains"],
             "Transportation": ["3800", "transportation"],
             "Transportation – Rail Transport": ["3801", "transportationrailtransport"],
             "Transportation – Road Transport": ["3802", "transportationroadtransport"],
             "Transportation – Water Transport": ["3803", "transportationwatertransport"],
             "Transportation – Air Transport": ["3804", "transportationairtransport"],
             "Government/ Other Organizations": ["6000", "governmentotherorganizations"],
             "Government – Others": ["6040", "governmentothers"],
             "Statutory Boards & Corporations": ["6080", "statutoryboardscorporations"],
             "Government-Owned Companies": ["6090", "governmentownedcompanies"],
             "Federal Government": ["6101", "federalgovernment"],
             "State Government": ["6102", "stategovernment"],
             "Local Government": ["6103", "localgovernment"],
             "Parastatals": ["6030", "parastatals"],
             "Manufacturing": ["3200", "manufacturing"],
             "Manufacturing – Flour Milling & Bakeries": ["3201", "manufacturingflourmillingbakeries"],
             "Manufacturing – Meat & Other Food Processing, Canning & Cold Storage": ["3202", "manufacturingmeatotherfoodprocessingcanningcoldstorage"],
             "Manufacturing – Beverages": ["3203", "beverages","manufacturingbeverages"],
             "Manufacturing – Textile & Apparel": ["3204", "manufacturingtextileapparel"],
             "Manufacturing – Footwear (Excluding Rubber Footwear)": ["3205", "manufacturingfootwearexcludingrubberfootwear"],
             "Manufacturing – Wood Products (Including Furniture)": ["3206", "manufacturingwoodproductsincludingfurniture"],
             "Manufacturing – Paper & Paper Products": ["3207", "manufacturingpaperpaperproducts"],
             "Manufacturing – Printing, Publishing": ["3208", "printingpublishing","manufacturingprintingpublishing"],
             "Manufacturing – Rubber Products (Including Rubber Footwear)": ["3209", "manufacturingrubberproductsincludingrubberfootwear"],
             "Manufacturing – Soaps, Oils & Detergents": ["3210", "manufacturingsoapsoilsdetergents"],
             "Manufacturing – Petroleum & Coal Products": ["3211", "manufacturingpetroleumcoalproducts"],
             "Manufacturing – Building Materials, Pottery, Ceramics & Glass": ["3212", "manufacturingbuildingmaterialspotteryceramicsglass"],
             "Manufacturing – Basic Metal Products": ["3213", "manufacturingbasicmetalproducts"],
             "Manufacturing – Miscellaneous Manufacturing & Processing": ["3214", "manufacturingmiscellaneousmanufacturingprocessing"],
             "Manufacturing – Other Non Metallic Products": ["3215", "manufacturing – other non metallic products"],
             "Manufacturing – Breweries": ["3216", "breweries","manufacturingbreweries"],
             "Manufacturing – Tobacco": ["3217", "manufacturingtobacco"],
             "Industrial Products, Machinery, Raw Materials": ["3517", "industrialproductsmachineryrawmaterials"],
             "Textiles, Apparels, Footwear": ["3519", "textiles","footwear","apparels","apparel","textilesapparelsfootwear"],
             "Mining and Quarrying": ["3100", "miningandquarrying"],
             "Coal Mining": ["3101", "coalmining"],
             "Metallic Mining (Tin, Ore, Iron, Zinc & Lead)": ["3103", "metallicminingtinoreironzinclead"],
             "Other Non-Metallic Mining (Including Quarrying and Sand pits)": ["3104", "othernonmetallicminingincludingquarryingandsandpits)"],
             "Consumer Durables": ["3512", "consumerdurables"],
             "Consumer Food Products": ["3513", "consumerfoodproducts"],
             "Imports And Domestic Trade": ["3514", "importsanddomestictrade"],
             "Industrial Food Products": ["3515", "industrialfoodproducts"],
             "Soaps, Oils, Detergents, Chemicals": ["3516","soaps","Chemical","Chemicals","oils","detergents", "soapsoilsdetergentschemicals"],
             "Merchants": ["3550","merchant" "merchants"],
             "Conglomerates": ["3551","conglomerate", "conglomerates"],
             "Retail Merchants": ["3552", "retailmerchant","retailmerchants"],
             "Wholesale Merchants": ["3553", "wholesalemerchant","wholesalemerchants"],
             "General Commerce": ["3500", "generalcommerce"],
             "Cocoa Export": ["3501", "cocoaexport"],
             "Groundnut, Groundnut Oil Export": ["3502","groundnut", "groundnutoilexport","groundnutgroundnutoilexport"],
             "Palm Produce Export": ["3503", "palmproduceexport"],
             "Cotton Export": ["3504", "cotton export"],
             "Hides & Skin Export": ["3505", "hidesskinexport"],
             "Rubber Products Exports": ["3506", "rubberproductsexports"],
             "Timber Products Exports": ["3507", "timberproductsexports"],
             "Other Agricultural Exports": ["3508", "otheragriculturalexports"],
             "Others": ["3509", "others"],
             "Non-Agricultural Exports": ["3518", "nonagriculturalexports"],
             "Legal Firms": ["5305","legalfirm", "legalfirms","lawyer"],
             "Management Consultants": ["5306", "managementconsultants"],
             "Personal": ["5307", "personal"],
             "Personal And Professional": ["5308", "personalandprofessional"],
             "Personal/ Professional": ['5300','personalprofessional'],
             "Auditors, Accountants, Receivers,Managers": ["5301","auditor", "auditors","accountants","receivers","managers","manager","auditorsaccountantsreceiversmanagers"],
             "Doctors (Traditional Orthodox)": ["5302","traditionalorthodox", "doctorstraditionalorthodox"],
             "Engineers": ["5303", "engineers"],
             "Finance and Insurance": ["4000", "financeandinsurance"],
             "Insurance Companies": ["4020", "insurancecompany","insurancecompanies"],
             "Finance Houses": ["4030", "financehouse","financehouses"],
             "Commercial Banks": ["4501", "commercialbank","commercialbanks"],
             "Merchant Banks": ["4502","merchantbank", "merchantbanks"],
             "Discount Houses": ["4503", "discounthouse","discounthouses"],
             "Other Financial Institutions": ["4504", "otherfinancialinstitutions"],
             "Hire Purchase & Leasing Companies": ["4505","hirepurchase","leasingcompany", "leasingcompanies","hirepurchaseleasingcompanies"],
             "Building Societies, Finance Co-operatives": ["4506","financecooperatives","financecooperative", "buildingsocieties","buildingsociety","buildingsocietiesfinancecooperatives"],
             "Communications – Other Communications": ["3805","communications","communication", "communicationsothercommunications"],
             "Hospitals, Medical Centres, Dental Clinics": ["3054","hospital","hospitals","medicalcentres","medicalcentre","medicalcenter","dentalclinics","dentalclinic", "hospitalsmedicalcentresdentalclinics"],
             "Travel Agencies, Shipping Agencies": ["3059", "travelagencies","travelagency","shippingagencies","shippingagency","travelagenciesshippingagencies"],
             "Hotels, Restaurants": ["3055", "restaurants","restaurant","hotels","hotel","hotelsrestaurants"],
             "Automobiles, Automobile Products": ["3510","automobiles","automobile","automobileproducts", "automobilesautomobileproducts"],
             "Universities": ["6020","university", "universities"],
             "Schools, Educational Institutions": ["3058","school","schools", "educationalinstitutions","educationalinstitution","schoolseducationalinstitutions"],
             "Crude Petroleum & Gas": ["3102", "petroleum","gas","crudepetroleumgas"],
             "General": ["3050", "general"],
             "Advertising Agencies": ["3051","advertising","advertisingagency", "advertisingagencies"],
             "Computer Software, Hardware": ["3052","computersoftware", "computersoftwarehardware"],
             "Dry Cleaners, Cleaning Agencies": ["3053","drycleaners", "drycleanerscleaningagencies"],
             "Mechanics, Auto Repair Workshops": ["3056","mechanic", "mechanicsautorepairworkshops"],
             "Other Miscellaneous Advances": ["3057", "other miscellaneous advances"],
             "Fashion Designers": ["5304", "fashiondesigner","fashiondesigners"],
             "Commodity Boards": ["6010","commodityboard" "commodityboards"],
             'Banker':['003','03','3','banker'],
             'Business':['004','04','4','business'],
             'CIVIL SERVANT':['008','08','8','civilservant'],
             'Lawyer':['022','22','lawyer'],
             'Administrator':['001','01','1','administrator'],
             'Chartered Accountant':['006','06','6','charteredaccountant'],
             'Cleric':['009','09','9','cleric'],
             'Consultant':['011','11','consultant'],
             'Doctor':['doctor','012','12'],
             'Engineer':['engineer','014','14'],
             'Farmer':['farmer','016','16'],
             'IT Professional':['20','020','itprofessional'],
             'Nursing':['026','nursing','26'],
             'Pilot':['pilot','028','28'],
             'Service':['service','033','33'],
             'Teacher':['teacher','035','35'],
             'Others':['other','036','36']
             }

# sec_dict = {
#     "Agriculture/Forestry": ["1",'01','001','agriculture','forestry', "agricultureforestry"],
#     "Building/Construction/Real Estate development": ["2", '02','002','building','construction','realestate','realestatedevelopment',"buildingconstructionrealestatedevelopment"],
#     "Transportation/Storage": ["3",'03','003','transportation','storage', "transportationstorage"],
#     "Government/MDAs": ["4",'04','004','government','mdas', "governmentmdas"],
#     "Manufacturing/Producing": ["5",'05','005','manufacturing','producing', "manufacturingproducing"],
#     "Mning/Quarrying/Mineral business": ["6",'06','006','mining','quarrying','mineral','mineralbusiness', "miningquarryingmineralbusiness"],
#     "Consumer durables/household items": ["7",'07','007','consumerdurables','householditems', "consumerdurableshouseholditems"],
#     "General Commerce/Traders/Importers/Exporters": ["8",'08','008','generalcommerce','traders','importers', "generalcommercetradersimportersexporters"],
#     "Professionals - Journalists/Lawyers/Accountants etc.": ["9",'09','009','journalists','journalist','lawyers','lawyer','accountants','accountant', "professionalsjournalistslawyersaccountantsetc"],
#     "Financial Services/banking/Insurance/capital Markets": ["10",'010','capitalmarkets','capitalmarket','financialservices','financialservice','banking','insurance', "financialservicesbankinginsurancecapitalmarkets"],
#     "Communications/Tele-communications": ["11",'011','communications','communication','telecommunications','telecommunication', "communicationstelecommunications"],
#     "Hospitals/Healthcare/Pharmaceuticals": ["12",'012','hospitals', 'hospital','healthcare','pharmaceutical','pharmaceuticals',"hospitalshealthcarepharmaceuticals"],
#     "Hotels/Hospitality/Leisure": ["13",'013','hotels','hotel','hospitality','leisure', "hotelshospitalityleisure"],
#     "Automobiles/Automobile Products": ["14",'014','automobiles','automobileproducts','automobileproduct', "automobilesautomobileproducts"],
#     "Education/Schools": ["15",'015','education','schools','school', "educationschools"],
#     "Oil & Gas": ["16",'016','oil','gas', "oilandgas"],
#     "Power/Energy": ["17",'017','power','energy', "powerenergy"],
#     "Water supply, sewage, waste management": ["18",'018','watersupply','sewage','wastemanagement', "watersupplysewagewastemanagement"],
#     "Arts/entertainment": ["19",'019', 'arts','entertainment',"artsentertainment"],
#     "Activities of extra-territorial organizations and bodies": ["20",'020', "activitiesofextraterritorialorganizationsandbodies"],
#     "Military/Law Enforcement": ["21",'021','military','lawenforcement', "militarylawenforcement"],
#     "Religious services": ["22",'022','religious', "religiousservices"],
#     "Others/Miscelaneous": ["23",'023','others','miscellaneous', "othersmiscellaneous"]
# }

Currency_dict = {"NGN": ["naira","n", "ng","ngn"],
                 "GBP": ["pounds", "gbp"],
                 "USD": ["dollars", "usd", "usdollars","dollar"],
                 "AFN": ["afn"],
                 "EUR": ["eur"],
                 "ALL": ["all"],
                 "DZD": ["dzd"],
                 "AOA": ["aoa"],
                 "XCD": ["xcd"],
                 "ARS": ["ars"],
                 "AMD": ["amd"],
                 "AWG": ["awg"],
                 "SHP": ["shp"],
                 "AUD": ["aud"],
                 "AZN": ["azn"],
                 "BSD": ["bsd"],
                 "BHD": ["bhd"],
                 "BDT": ["bdt"],
                 "BBD": ["bbd"],
                 "BYN": ["byn"],
                 "BZD": ["bzd"],
                 "XOF": ["xof"],
                 "BMD": ["bmd"],
                 "BTN": ["btn"],
                 "BOB": ["bob"],
                 "BAM": ["bam"],
                 "BWP": ["bwp"],
                 "BRL": ["brl"],
                 "BND": ["bnd"],
                 "BGN": ["bgn"],
                 "BIF": ["bif"],
                 "CVE": ["cve"],
                 "KHR": ["KHR"],
                 "XAF": ["xaf"],
                 "CAD": ["cad"],
                 "KYD": ["kyd"],
                 "NZD": ["nzd"],
                 "CLP": ["clp"],
                 "CNY": ["cny"],
                 "COP": ["cop"],
                 "KMF": ["kmf"],
                 "CDF": ["cdf"],
                 "none": ["none"],
                 "CRC": ["crc"],
                 "HRK": ["hrk"],
                 "CUP": ["cup"],
                 "ANG": ["ang"],
                 "CZK": ["czk"],
                 "DKK": ["dkk"],
                 "DJF": ["djf"],
                 "DOP": ["dop"],
                 "EGP": ["egp"],
                 "ERN": ["ern"],
                 "ETB": ["etb"],
                 "FKP": ["fkp"],
                 "FJD": ["fjd"],
                 "XPF": ["xpf"],
                 "GMD": ["gmd"],
                 "GEL": ["gel"],
                 "GHS": ["ghs"],
                 "GIP": ["gip"],
                 "GTQ": ["gtq"],
                 "GGP": ["ggp"],
                 "GNF": ["gnf"],
                 "GYD": ["gyd"],
                 "HTG": ["htg"],
                 "HNL": ["hnl"],
                 "HKD": ["hkd"],
                 "HUF": ["huf"],
                 "ISK": ["isk"],
                 "INR": ["inr"],
                 "IDR": ["idr"],
                 "XDR": ["xdr"],
                 "IRR": ["irr"],
                 "IQD": ["iqd"],
                 "IMP": ["imp"],
                 "ILS": ["ils"],
                 "JMD": ["jmd"],
                 "JPY": ["jpy"],
                 "JEP": ["jep"],
                 "JOD": ["jod"],
                 "KZT": ["kzt"],
                 "KES": ["kes"],
                 "KWD": ["kwd"],
                 "KGS": ["kgs"],
                 "LAK": ["lak"],
                 "LBP": ["lbp"],
                 "LSL": ["lsl"],
                 "LRD": ["lrd"],
                 "LYD": ["lyd"],
                 "CHF": ["chf"],
                 "MOP": ["mop"],
                 "MKD": ["mkd"],
                 "MGA": ["mga"],
                 "MWK": ["mwk"],
                 "MYR": ["myr"],
                 "MVR": ["mvr"],
                 "MRO": ["mro"],
                 "MUR": ["mur"],
                 "MXN": ["mxn"],
                 "MDL": ["mdl"],
                 "MNT": ["mnt"],
                 "MAD": ["mad"],
                 "MZN": ["mzn"],
                 "MMK": ["mmk"],
                 "NAD": ["nad"],
                 "NPR": ["npr"],
                 "NIO": ["nio"],
                 "KPW": ["kpw"],
                 "NOK": ["nok"],
                 "OMR": ["omr"],
                 "PKR": ["pkr"],
                 "PGK": ["pgk"],
                 "PYG": ["pyg"],
                 "PEN": ["pen"],
                 "PHP": ["php"],
                 "PLN": ["pln"],
                 "QAR": ["qar"],
                 "RON": ["ron"],
                 "RUB": ["rub"],
                 "RWF": ["rwf"],
                 "WST": ["wst"],
                 "STD": ["std"],
                 "SAR": ["sar"],
                 "RSD": ["rsd"],
                 "SCR": ["scr"],
                 "SLL": ["sll"],
                 "SGD": ["sgd"],
                 "SBD": ["sbd"],
                 "SOS": ["sos"],
                 "ZAR": ["zar"],
                 "GBP": ["pounds", "pound","gbp"],
                 "KRW": ["krw"],
                 "SSP": ["ssp"],
                 "LKR": ["lkr"],
                 "SDG": ["sdg"],
                 "SRD": ["srd"],
                 "SZL": ["szl"],
                 "SEK": ["sek"],
                 "SYP": ["syp"],
                 "TWD": ["twd"],
                 "TJS": ["tjs"],
                 "TZS": ["tzs"],
                 "THB": ["thb"],
                 "TOP": ["top"],
                 "TTD": ["ttd"],
                 "TND": ["tnd"],
                 "TRY": ["try"],
                 "TMT": ["tmt"],
                 "UGX": ["ugx"],
                 "UAH": ["uah"],
                 "AED": ["aed"],
                 "UYU": ["uyu"],
                 "UZS": ["uzs"],
                 "VUV": ["vuv"],
                 "VEF": ["vef"],
                 "VND": ["vnd"],
                 "YER": ["yer"],
                 "ZMW": ["zmw"]}
AccountStatus_dict = {
    'Open': ['001', 'open', '01', '1', 'active'],
    'Closed': ['002', 'closed', '02', '2'],
    'Writtenoff': ['003', 'written off', 'written0ff', '03', '3']
}
Loan_dict = {'Commercial Overdraft': ['commercialoverdraft', '1', '01', '001', 'CommercialOverdraft'],
                 'Commercial Credit Card Loan': ['commercialcreditcardloan', '2', '02', '002', 'CommercialCreditCardLoan'],
                 'Commercial revolving renewable short-term credit': ['commercialrevolvingrenewableshorttermcredit', '3', '03', '003', 'CommercialRevolvingCredit'],
                 'Commercial mortgage loan including mortgage re-financing': ['commercialmortgageloanincludingmortgagerefinancing', '4', '04', '004'],
                 'Commercial rent facility': ['commercialrentfacility', '5', '05', '005'],
                 'Commercial Land purchase financing': ['commerciallandpurchasefinancing', '6', '06', '006'],
                 'Commercial/Business Auto Loan': ['commercialbusinessautoloan','commercialautoloan','businessautoloan', '7', '07', '007'],
                 'Commercial/Business equipment asset/leasing/financing': ['commercialbusinessequipmentassetleasingfinancing', 'businessequipmentasset','8', '08', '008'],
                 'Commercial/Business fixed term loan': ['commercialbusinessfixedtermloan','commercialfixedtermloan','businessfixedtermloan', '9', '09', '009'],
                 'Foreign-denominated commercial loan': ['foreigndenominatedcommercialloan', '10', '010'],
                 'Commercial investment loan': ['commercialinvestmentloan', '11', '011'],
                 'Local Purchase Order (LPO)/supply contract financing': ['localpurchaseorderlposupplycontractfinancing','localpurchaseorder','supplycontractfinancing','lpo', '12', '012'],
                 'Distributor/supplier credit finance': ['distributorsuppliercreditfinance', '13', '013'],
                 'Invoice discounting/account receivable/Warehouse receipt finance': ['invoicediscountingaccountreceivablewarehousereceiptfinance','invoicediscounting','accountreceivable','warehousereceiptfinance', '14', '014'],
                 'Oil and Gas contract finance': ['oilandgascontractfinance', 'oilgas','oilcontractfinance','gascontractfinance','oilgascontractfinance', '15', '015'],
                 'Project Financing,/Long-term infrastructure, Industrial, Public Service finance, Non-Recourse Debt, Non-Recourse Finance': ['projectfinancinglongterminfrastructureindustrialpublicservicefinancenonrecoursedebtnonrecoursefinance', '16', '016','projectfinancing','longterminfrastructure','industrial','publicservicefinance','nonrecoursedebt','nonrecoursefinance'],
                 'Build-Operate-Transfer (BOT) Contract/Finance': ['buildoperatetransferfinance','botcontract','bottransfer','buildoperatetransfercontract','buildoperatetransferbotcontractfinance', '17', '017'],
                 "Banker's acceptance facility": ["Bankersacceptancefacility", "Bankeracceptancefacility",'18', '018'],
                 'Commercial paper': ['commercialpaper', '19', '019'],
                 'International trade finance /Letter of Credit': ['internationaltradefinanceletterofcredit','internationaltradefinance', 'letterofcredit','20', '020'],
                 'Import Finance/Stock replacement facility': ['importfinance','importfinancestockreplacementfacility','stockreplacementfacility', '21', '021'],
                 'Export Finance': ['exportfinance', '22', '022'],
                 'Bond and guarantees (bid bonds, Customs & Excise bonds, Advance payment guarantee, performance bonds, etc.': ['bondandguaranteesbidbondscustomsexcisebondsadvancepaymentguaranteeperformancebondsetc',   '23', '023','bondandguarantees', 'bidbonds','bidbond', 'customsexcisebonds', 'customsexcisebond', 'advancepaymentguarantee','performancebonds','performancebond'],
                 'Loan syndication; Competitive Bid Option': ['loansyndication','loansyndicationcompetitivebidoption','competitivebidoption', '24', '024'],
                 'Business travel loan': ['businesstravelloan', '25', '025'],
                 'Business agriculture finance': ['businessagriculturefinance', '26', '026'],
                 'Treasury bills': ['treasurybills','treasurybill', '27', '027'],
                 'Government-backed loan': ['governmentbackedloan', '28', '028'],
                 'Microfinance or small proprietor loan': ['Microfinanceorsmallproprietorloan', 'Microfinanceproprietorloan', 'smallproprietorloan','29', '029'],
                 'Personal Overdraft': ['personaloverdraft', '30', '030'],
                 'Personal Credit Card Loan': ['personalcreditcardloan', '31', '031'],
                 'Personal revolving renewable short-term credit': ['personalrevolvingrenewableshorttermcredit', '32', '032'],
                 'Personal secured loan': ['personalsecuredloan', '33', '033'],
                 'Personal home mortgage including mortgage refinance': ['personalhomemortgageincludingmortgagerefinance', 'mortgagerefinance','personalhomemortgage','34', '034'],
                 'Residential rent facility': ['residentialrentfacility', '35', '035'],
                 'Personal land purchase financing': ['personallandpurchasefinancing','landpurchase', '36', '036'],
                 'National Housing Fund Loan': ['nationalhousingfundloan', '37', '037'],
                 'Personal Auto Loan': ['personalautoloan', '38', '038'],
                 'Personal/consumer equipment/asset hire purchase/leasing/financing': ['personalconsumerequipmentassethirepurchaseleasingfinancing','consumerequipment', 'assethirepurchase','39', '039'],
                 'Personal fixed term loan': ['Personalfixedtermloan', '40', '040'],
                 'Payday Loan or salary advance': ['paydayloanorsalaryadvance','paydayloan','salaryadvance', '41', '041'],
                 'Personal bullet or one-time loan payment': ['personalbulletoronetimeloanpayment','onetimeloanpayment','personalbullet', '42', '042'],
                 'Foreign-denominated personal loan': ['foreigndenominatedpersonalloan', 'foreignpersonalloan', '43', '043'],
                 'Personal investment loan': ['personalinvestmentloan', '44', '044'],
                 'Education or student loan': ['educationorstudentloan','educationloan','studentloan', '45', '045'],
                 'Shares acquisition/purchase or margin loan': ['sharesacquisitionpurchaseormarginloan','purchaseormarginloan','sharesacquisition', '46', '046'],
                 'Personal travel or vacation loan': ['personaltravelorvacationloan','personaltravel','vacationloan', '47', '047'],
                 'Personal agriculture finance': ['personalagriculturefinance', '48', '048'],
                 'Darah - Operating Lease':['darahoperatinglease','49','049'],
                 'Ijarah wa Igtina- Finance Lease':['ijarahwaigtinafinancelease','50','050'],
                 'Mudaraba- Trustee Partnership':['mudarabatrusteepartnership','51','051'],
                 'Nusharaua/Musharakah- Equity Partnership':['nusharauamusharakahequitypartnership','nusharauaequitypartnership','musharakahequitypartnership','52','052'],
                 "Istina'- Manufacturing/Production Finance":["istinamanufacturingproductionfinance",'productionfinance','istinamanufacturing','53','053'],
                 'Salam- Advance Payment For Agric Finance':['Salamadvancepaymentforagricfinance','advancepaymentforagricfinance','54','054'],
                 'Commodity Muraba':['commoditymuraba','55','055'],
                 'Wakak- Agency':['wakakagency','56','056'],
                 'Qard Hassan- Benevolt Loan':['qardhassanbenevoltloan','benevoltloan','qardhassan','57','057'],
                 'Bai Muajjal - Deferred Sale/Credit sale':['baimuajjaldeferredsalecreditsale','creditsale','baimuajjaldeferredsale','58','058'],
                 'Sukur':['sukur','59','059'],
                 'Istijrar - Continous Sale':['istijrarcontinoussale','60','060'],
                 'Murabaha -Mark Up Sale':['murabahamarkupsale','61','061'],
                 'Bai-Assarf -Foreign Exchange/FX Trade':['baiassarfforeignexchangefxtrade','baiassarfforeignexchange','fxtrade','62','062'],
                 'Wakala - Agency Guarantee':['wakalaagencyguarantee','63','063'],
                 'Kafala -Guarantee':['kafalaguarantee','64','064']
                 }

Repayment_dict = {'Weekly':['d','w','1','days','day','weekly','daily','01','001','day','week'],
                  'Forthnightly':['f','2','forthnight','02','002','forth','forthnightly'],
                  'Monthly':['m','month','monthly', '3','03','003'],
                  'Quarterly':['q','quarter','quarterly','4','04','004'],
                  '6 Months':['5','sixmonth','sixmonths','6months','6month','halfyear','half year','05','005'],
                  'Yearly': ['y','yearly','year','6','06','006','one year','1year'],
                  'Bullet':['b','bullet', '7','07','007']
}
Classification_dict = {'Performing':['001', 'performing','1','01','perform',"performingloansperformingadvances", "performing loansperforming advances"],
                       'Watchlist':['002','watchlist','02','2',"pass and watch"],
                       'Sub standard':['003','sub standard','substandard','03','3','sub'],
                       'Doubtful':['004', 'doubtful','04','4'],
                       'Lost':['005','lost','05','5']
}
Collateraltype_dict = { 'Real Estate/Land & Building':['001','realestatelandbuilding','01','1','realestate','land','building'],
                      'Automobile':['002','Automobile','02','2'],
                      'Plant and Equipment':['003','plantequipment','plantandequipment','equipment','plant','03','3'],
                      'Natural Reserves':['004','naturalreserves','natural','reserves','04','4'],
                      'Marketable Securities':['005','marketablesecurities','marketable','securities','05','5'],
                      'Accounts Receivables and Inventory':['006','accountsreceivablesandinventory','accountsreceivable','accountsreceivables','inventory','accountsreceivablesinventory','06','6'],
                      'Cash':['007','cash','07','7'],
                      'Personal Guarantees':['008','personalguarantees','personalguarantee','personal','guarantees','08','8'],
                      'Post Dated Cheques':['009','postdatedcheques','postcheques','datedcheques','cheques','09','9'],
                      'Dormicilliation':['010','dormicilliation','10']}


ConsuToComm={
    'DATA':['DATA'],
    'BUSINESSREGISTRATIONNUMBER':[''],
    'BUSINESSNAME':['SURNAME'],
    'BUSINESSTRADINGNAME':[''],
    'BUSINESSCATEGORY':[''],
    'BUSINESSSECTOR':[''],
    'DATEOFINCORPORATION':['DATEOFBIRTH'],
    'CUSTOMERID':['CUSTOMERID'],
    'CUSTOMERBRANCHCODE':['BRANCHCODE'],
    'BUSINESSOFFICEADDRESSLINE1':['PRIMARYADDRESSLINE1'],
    'BUSINESSOFFICEADDRESSLINE2':['PRIMARYADDRESSLINE2'],
    'BUSINESSOFFICEADDRESSCITYLGA':['PRIMARYADDRESSCITY'],
    'BUSINESSOFFICEADDRESSSTATE':['PRIMARYADDRESSSTATE'],
    'BUSINESSOFFICEADDRESSCOUNTRY':['PRIMARYADDRESSCOUNTRY'],
    'BUSINESSOFFICEADDRESSPOSTCODE':['PRIMARYADDRESSPOSTCODE'],
    'EMAILADDRESS':['EMAILADDRESS'],
    'SECONDARYADDRESSLINE1':['SECONDARYADDRESSLINE1'],
    'SECONDARYADDRESSLINE2':['SECONDARYADDRESSLINE2'],
    'SECONDARYADDRESSCITYLGA':['SECONDARYADDRESSCITYLGA'],
    'SECONDARYADDRESSSTATE':['SECONDARYADDRESSSTATE'],
    'SECONDARYADDRESSCOUNTRY':['SECONDARYADDRESSCOUNTRY'],
    'SECONDARYADDRESSPOSTCODE':[''],
    'TAXID':[''],
    'PRIMARYPHONENUMBER':['MOBILENUMBER'],
    'SECONDARYPHONENUMBER':['WORKTELEPHONE'],
    'ACCOUNTNUMBER':['ACCOUNTNUMBER'],
    'ACCOUNTSTATUS':['ACCOUNTSTATUS'],
    'ACCOUNTSTATUSDATE':['ACCOUNTSTATUSDATE'],
    'LOANEFFECTIVEDATE':['LOANEFFECTIVEDATE'],
    'DEFEREDPAYMENTDATE':['DEFEREDPAYMENTDATE'],
    'CREDITLIMIT':['CREDITLIMIT'],
    'AVAILEDLIMIT':['AVAILEDLIMIT'],
    'OUTSTANDINGBALANCE':['OUTSTANDINGBALANCE'],
    'CURRENTBALANCEDEBITIND':['CURRENTBALANCEDEBITIND'],
    'INSTALMENTAMOUNT':['INSTALMENTAMOUNT'],
    'CURRENCY':['CURRENCY'],
    'DAYSINARREARS':['DAYSINARREARS'],
    'OVERDUEAMOUNT':['OVERDUEAMOUNT'],
    'FACILITYTYPE':['FACILITYTYPE'],
    'FACILITYTENOR':['FACILITYTENOR'],
    'REPAYMENTFREQUENCY':['REPAYMENTFREQUENCY'],
    'LASTPAYMENTDATE':['LASTPAYMENTDATE'],
    'LASTPAYMENTAMOUNT':['LASTPAYMENTAMOUNT'],
    'MATURITYDATE':['MATURITYDATE'],
    'LOANCLASSIFICATION':['LOANCLASSIFICATION'],
    'LEGALCHALLENGESTATUS':['LEGALCHALLENGESTATUS'],
    'LITIGATIONDATE':['LITIGATIONDATE'],
    'CONSENTSTATUS':['CONSENTSTATUS'],
    'LOANSECURITYSTATUS':['LOANSECURITYSTATUS'],
    'COLLATERALTYPE':['COLLATERALTYPE'],
    'COLLATERALDETAILS':['COLLATERALDETAILS'],
    'PREVIOUSACCOUNTNUMBER':['PREVIOUSACCOUNTNUMBER'],
    'PREVIOUSNAME':['PREVIOUSNAME'],
    'PREVIOUSCUSTOMERID':['PREVIOUSCUSTOMERID'],
    'PREVIOUSBRANCHCODE':['PREVIOUSBRANCHCODE'],
    'NUMBEROFDIRECTORS':[''],
    'PRINCIPALOFFICER1SURNAME':['INDIVIDUALGUARANTORSURNAME'],
    'PRINCIPALOFFICER1FIRSTNAME':['INDIVIDUALGUARANTORFIRSTNAME'],
    'PRINCIPALOFFICER1MIDDLENAME':['INDIVIDUALGUARNTORMIDDLENAME'],
    'PRINCIPALOFFICER1DATEOFBIRTH':['GUARANTORDATEOFBIRTHINCORPORATION'],
    'PRINCIPALOFFICER1GENDER':['GUARANTORGENDER'],
    'PRINCIPALOFFICER1PRIMARYADDRESSLINE1':['GUARANTORPRIMARYADDRESSLINE1'],
    'PRINCIPALOFFICER1PRIMARYADDRESSLINE2':['GUARANTORPRIMARYADDRESSLINE2'],
    'PRINCIPALOFFICER1CITY':['GUARANTORPRIMARYADDRESSCITYLGA'],
    'PRINCIPALOFFICER1STATE':['GUARANTORPRIMARYADDRESSSTATE'],
    'PRINCIPALOFFICER1COUNTRY':['GUARANTORPRIMARYADDRESSCOUNTRY'],
    'PRINCIPALOFFICER1NATIONALID':[''],
    'PRINCIPALOFFICER1DRIVERSLICENSENUMBER':[''],
    'PRINCIPALOFFICER1BVNNUMBER':[''],
    'PRINCIPALOFFICER1PASSPORTNUMBER':[''],
    'PRINCIPALOFFICER1OTHERIDNUMBER':[''],
    'PRINCIPALOFFICER1PHONENUMBER':['GUARANTORPRIMARYPHONENUMBER'],
    'PRINCIPALOFFICER1EMAILADDRESS':[''],
    'PRINCIPALOFFICER1POSITIONINBUSINESS':[''],
    'PRINCIPALOFFICER2SURNAME':[''],
    'PRINCIPALOFFICER2FIRSTNAME':[''],
    'PRINCIPALOFFICER2MIDDLENAME':[''],
    'PRINCIPALOFFICER2DATEOFBIRTH':[''],
    'PRINCIPALOFFICER2GENDER':[''],
    'PRINCIPALOFFICER2PRIMARYADDRESSLINE1':[''],
    'PRINCIPALOFFICER2PRIMARYADDRESSLINE2':[''],
    'PRINCIPALOFFICER2CITY':[''],
    'PRINCIPALOFFICER2STATE':[''],
    'PRINCIPALOFFICER2COUNTRY':[''],
    'PRINCIPALOFFICER2NATIONALID':[''],
    'PRINCIPALOFFICER2DRIVERSLISCENCENUMBER':[''],
    'PRINCIPALOFFICER2BVNNUMBER':[''],
    'PRINCIPALOFFICER2PASSPORTNUMBER':[''],
    'PRINCIPALOFFICER2OTHERIDNUMBER':[''],    
    'PRINCIPALOFFICER2PHONENUMBER':[''],
    'PRINCIPALOFFICER2EMAILADDRESS':[''],
    'PRINCIPALOFFICER2POSITIONINBUSINESS':['']}