consu_mapping = {
        # 'DATA':['DATA','data'],
        'CUSTOMERID': ['customerid','customernumber','cusid','idno','custid','customeridind','customerkey','custcode','subjectidentificationnumber','customerno', 'customersid', 'idno', 'otheridnumber', 'customernumber', 'custno', 'customerkey', 'subjectidentificationnumber', 'custcode', 'customerid', 'customeridorcustomernumber', 'subjectidno', 'subjectidentificationnumber', 'customersnumber', 'sheet1customerid', 'idno', 'consumerid'],
        'BRANCHCODE': ['branchcode','branchidno','brchcode','branch','customerbranchcode','customersbranchcode','branchid','branchidentificationnumber', 'branchidnumber','branchidentificationno'],
        'SURNAME': ['surname','Surname','surname','lastname', 'Surname', 'surname', 'fullname', 'mfassociationname', 'description', 'subfullname', 'fullname', 'subjectfullname', 'surnamefirstnameothernames', 'fullnames', 'acctname', 'name', "customersname", 'businessname', 'lastname', 'subjectfamilynamelastname', 'subjectfamilynamelastname', 'registeredname', 'customername', 'businessname', 'surname 11'],
        'FIRSTNAME': ['firstname','first', 'subjectfirstname'],
        'MIDDLENAME': ['middlename', 'othernames', 'middlenames','othername', 'subjectsmiddlename', 'subjectmiddlename'],
        'DATEOFBIRTH': ['dateofbirth','dateofloanfacilitydisbursement','dateofcommencement','birthofdate','datebirth','birthdate','dob','dateofincorporation', 'birthday', 'dateofbirthddmmyyyy', 'birthdateddmmyyyy', 'dob', 'birthdaymonthyear', 'birthday', 'birthdateyyyymmdd', 'dateofbirthyyyymmdd', 'dateofbirthyyyymmdd', 'birthdateddmmyyyy'],
        'NATIONALIDENTITYNUMBER': ['nationalidnumber','nationalidno','nin','nationalidentityno','nationalidentitynumber','nationalidentitynumber','nationalidcode','nationalid','natidcardnum','nationalidcode','nationalidnumber','subjectidentificationnumber','subjectnationalidentificationcode'],
        'DRIVERSLICENSENUMBER': ['driverslicence','driverlicence','driverlicense','driverslicense','driverslicenseno','driverlicenseno','driverslicenceno','driverlicenceno','driverslicensenumber','driverlicensenumber','driverslicencenumber','driverlicencenumber','DriversLicenseNo', 'driverslicenseno'],
        'BVNNUMBER': ['bvnno','bankverificationnumber','bankverificationnum','customerbvn','otheridnumber','bvn','bankbvn','bankverificationno'],
        'PASSPORTNUMBER' : ['passportno','passport no','passportnumber','passportno','passportnumber','passport','passportno','passportid','psprtnum','subjectinternationalpassport'],
        'PENCOMIDNUMBER': ['pencomidnumber','pencom id number','pencomid number','pencomidnumber', 'pencomid', 'pencomnumber', 'pensioncommissionnumber', 'pensionnumber', 'subjectpencomidnumber'],
        'OTHERID' : ['otherid','othersid','individualtaxidno','otheridnumber','otheridnum','otheridno'],
        'GENDER': ['gender','gender01','sex','subjectgender'],
        'NATIONALITY': ['nationality','subjectnationalitycountry','subjectnationalitycountry','nationalit','nationality', 'citizenship', 'subjectnationality'],
        'MARITALSTATUS': ['maritalstatus','custmaritalstatus','customermaritalstatus','marital'],
        'MOBILENUMBER': ['mobilephonenumbers','phone','mobilephonenumber','mobilephone','moblenumber','moblephone','mobilenumber','phonenumber', 'mobile','telephone', 'telephonenumber', 'contactnumber', 'subjectphone', 'tel', 'telno', 'subjecttellno', 'subjecttelno'],
        'PRIMARYADDRESSLINE1': ['primaryaddrline1','primaryadressLine1','primaryaddress1','primaryaddressline1','primaryaddressline1', 'address1','addressline1','address1line1','resdaddr1','addresstype1','address1','address','residentialaddress','addresstype1line1','primaryaddressline1','custpermaddr1','residentialaddressline1','primaryaddressline1','postaladdress1','businessofficeaddressline1','residentialaddressline1','addresstype1line1','primaryaddressline1','addresstype1','buslinetype1','businessofficeaddressline1','addresstype1line1','locationaddressline1','address', 'residentialaddress', 'homeaddress','subjectaddress', 'addr', 'location'],
        'PRIMARYADDRESSLINE2': ['primaryaddrline2','primaryaddressline2','addressline2','residentialaddress2','residentialaddress2','residentialaddress2','address2','addressline2','address1line2','addresstype1line2','primaryaddressline2','custpermaddr2','residentialaddressline2','primaryaddressline2','businessofficeaddressline2','residentialaddressline2','primaryaddressline2','buslinetype2','address2','addresstype1line2','locationaddressline2'],
        'PRIMARYADDRESSCITY': ['primaryaddresscity','primarycitylga','primarycitylga','addressline3','addresscity','residentialaddress3','residentialaddress3','address3','addressline3','address1city','addresstype1city','lga','addresstype1lgacity','primarycitylga','addresstype1lgacity','addresstype1citylga','localgovernmentoforigin','cityaddr','city'],
        'PRIMARYADDRESSSTATE': ['primaryaddressstate','primaryaddress','primarystate','addressstate','residentialaddress4','residentialaddress4','state','address1state','addresstype1state','primarystate','addresstype1state','stateoforigin','addresstype1citylga','stateaddr'],
        'PRIMARYADDRESSCOUNTRY': ['primaryaddresscountry','primarycountry','primarycountry','addresscountry','country','address1country','addresstype1country','primarycountry','custpermcntrycode','custcomucntrycode','addresstype1country','countaddr'],
        'PRIMARYADDRESSPOSTCODE':['primaryaddresspostcode','postalcdeofresaddr'],
        'EMPLOYMENTSTATUS': ['employmentstatus','employmentstat','empstatus'],
        'OCCUPATION': ['occupation','ocupation','natureofbusiness','employerdetail','occup'],
        'BUSINESSCATEGORY': ['businesscategory','businescategory','buscate','businesscat','buscat'],
        'BUSINESSSECTOR': ['businesssector','bussector','bussec','businesssec'],
        'BORROWERTYPE': ['borrowertype','borowtype'],
        'TAXID': ['taxid','individualtaxidno','individualtaxid','taxidno','individualtax'],
        'PICTUREFILEPATH': ['picturefilepath','picfile'],
        'EMAILADDRESS': ['emailaddress','email','emailadd','subjectemail', 'mail'],
        'EMPLOYERNAME': ['employername','employer','employerdetail','employerid'],
        'EMPLOYERADDRESSLINE1': ['employeraddrline1','employeraddress1','employeraddressline1','employeraddline1','emploeraddress1','employeraddress','employeraddress1','custempaddr1','empaddr1'],
        'EMPLOYERADDRESSLINE2': ['employeraddrline2','employeraddress2','employeraddressline2','employeraddline2','emploeraddress2','employeraddress2','employeraddress2','custempaddr2','empaddr2'],
        'EMPLOYERCITY': ['employerlgacity','employercity','emploeraddress3','employeraddress3','custempcitycode','empcity',],
        'EMPLOYERSTATE': ['employerstate','emploeraddress4','employerstate','custempstatecode','empstate','employersstate'],
        'EMPLOYERCOUNTRY': ['employercountry','custcomucntrycode1','empcountr','employercountry','employerscountry'],
        'TITLE': ['title','customertitle'],
        'PLACEOFBIRTH': ['placeofbirth','pob','birthplace','placebirth'],
        'WORKTELEPHONE': ['workphone','mobile','moilephone','worktelephone','databasephonenumber','phoneno','telephonenumber','cellulartelephone','hometelephone','phonenumber','phoneno','mobilephone','workphone','custcomuphonenum1','mobilenumber','telephone','worktelephone'],
        'HOMETELEPHONE': ['homephone','telephone','hometelephone','cellulartelno','homephone','custcomuphonenum2','phonenumber'],
        'SECONDARYADDRESSLINE1': ['secondaryaddressline1','postaladdress1','address2line1','residentialaddressline1','secaddr1','addresstype2line3'],
        'SECONDARYADDRESSLINE2': ['secondaryaddressline2','secondaryaddressline11','secondaryaddressline12','postaladdress','postaladdress2','address2line2','residentialaddressline2','secondaryaddressline2','secaddr2','addresstype2line2','secaddline2','secadd2'],
        'SECONDARYADDRESSCITYLGA': ['secondaryaddresscitylga','postaladdress3','address2city','seccity','addresstype2city','secaddcity','secaddcitylga','secaddlga','Secondary Address LGA/CITY'],
        'SECONDARYADDRESSSTATE': ['secondaryaddressstate','postaladdress4','address2state','secaddtate','secstate','addresstype2state'],
        'SECONDARYADDRESSCOUNTRY': ['secondaryaddresscountry','address2country','postaladdress3','secondaryaddresscountry','seccountr'],
        'SECONDARYADDRESSPOSTCODE': ['secondaryaddresspostcode','postalcdeofresaddr1','address2postcode','postaladdress'],
        'SPOUSESURNAME': ['spousesurname','spousessurname','spousessur','spousesur','spouseslastname','spouselastname'],
        'SPOUSEFIRSTNAME': ['spousesfirstname','spousefirstname','spousefir','spousefirst','spousef'],
        'SPOUSEMIDDLENAME': ['spousesmiddlename','spousemiddlename','spousesothername','spouseothername']
}

comm_mapping = {
        # 'DATA':['Data'],
        'BUSINESSREGISTRATIONNUMBER': ['businessidentificationnumber','businesidentificationnumber','businessid','businessidno','businessidentificationno','businessidentificationno','businessregistrationnumber','businesidentificationnumber','regno','regno','businessidno','rcnumber','busregnumber','businessregistrationnumber','businessregno','businessidentificationno','busregnum','businessregistrationnumber','subjectmicroenterpriseregistrationnumber','businessidentificationno','businessidentificationnumber','subjectbusinessregistrationnumber','trusteeregisteredno','refno','busregno','dob','businnessregno'],
        'BUSINESSNAME': ['businessname','businesname','surname','customername','surnamefirstnameothernames','fullname','mfassociationname','description','registeredname','surname1','subjectfamilynamelastname','subjectregisteredname','acctname','subjectmicroenterprisename','businessname1','subjectregisteredname','registeredname','subfullname','customername','businessregisteredname'],
        'BUSINESSTRADINGNAME':['BUSINESSTRADINGNAME','businesstradingname'],
        'BUSINESSCATEGORY': ['businesscategory','businescategory','businesscat','buscat','bizcat','natureofbusiness', 'corporatebizcategory', 'buscategory', 'businesstype111'],
        'BUSINESSSECTOR': ['bussinesssector','bussinessector','bussec','businesssec','industrysector','industrysector','businesscorporatetype','businesscorptype','businescorpotype','businesscorpotype','businescorporatetype','industrialsector','subjectsmicroenterprisemainbusinesslineoccupationtype','businesscorptype'],
        'DATEOFINCORPORATION': ['dateofincoporation','dateofincorporation','dateofincorpo','commencedate','dateofbirth','registrationdate','dateofincorp','dateofcommencement','birthdate','dateofincorporation','dateofcommencement','subjectmicroenterpriseregistrationdatebusinessregistration','dateofregistration','regdate','enterpriseregistrationdate','businessregdate'],
        'CUSTOMERID': ['customerid','customerno','customernumber','customerkey','subjectidentificationnumber','custcode','customerid','custid','customeridorcustomernumber','idno','customersnumber','custno','subjectidno','customeridcorp'],
        'CUSTOMERBRANCHCODE': ['customersbranchcode','branchcode','branchidno','brchcode','branch','customerbranchcode','branchid',  'branchidentificationnumber', 'dataproviderbranchidentificationnumber'],
        'BUSINESSOFFICEADDRESSLINE1': ['businessofficeaddressline1','businessaddress1','businessaddressline1','businessofficeaddressline1', 'primaryaddressline1', 'residentialaddress1', 'residentialaddress1', 'locationaddress1', 'businessofficeline1', 'address1', 'addressline1', 'locationaddr1', 'addresstype1', 'address1', 'locationaddressline1', 'residentialaddress', 'businessofficeaddress1', 'custcomuaddr1', 'residentialaddress1', 'addresstype1line1', 'locationaddressline1', 'businessoffice', 'address', 'address1line1', 'primaryaddressline1', 'primaryessline1addresstype1line1'],
        'BUSINESSOFFICEADDRESSLINE2': ['businessofficeaddressline2','businessaddress2','businessaddressline2', 'primaryaddressline2', 'residentialaddress2', 'locationaddressline2', 'locationaddress2', 'address2', 'addressline2', 'locationaddr2', 'addresstype2', 'businessofficeaddress2', 'custcomuaddr2', 'residentialaddressline2', 'residentialaddress2', 'businessofficeaddressline2', 'addresstype2line1', 'locationaddressline2', 'addresstype1line2', 'address1line2', 'primaryaddreessline2', 'addresstype1line2'],
        'BUSINESSOFFICEADDRESSCITYLGA': ['businesscitylga','businesscity','businessofficeaddresscitylga','citylga', 'bcitylga', 'addresstype1citylga', 'residentialaddress3', 'citylga', 'address1city', 'primarycitylga', 'city'],
        'BUSINESSOFFICEADDRESSSTATE': ['businessstate','businessofficeaddressstate','state','primarystate', 'locationaddress4', 'addresstype1state', 'addresstype2state', 'custcomustatecode', 'residentialaddress4', 'addresstype1state', 'address1state'],
        'BUSINESSOFFICEADDRESSCOUNTRY': ['businesscountry','businessofficeaddresscountry','country','primarycountry', 'custcomucntrycode', 'addresstype1country', 'address1country'],
        'BUSINESSOFFICEADDRESSPOSTCODE':['BUSINESSOFFICEADDRESSPOSTCODE','businessofficeaddresspostcode'],
        'EMAILADDRESS': ['emailaddress','emailid','email'],
        'SECONDARYADDRESSLINE1': ['secondaryaddress1','secondaryaddressline1', 'postaladdress1', 'postaladdressline1', 'postalcode1', 'secondaryaddressline1', 'custpermaddr1', 'secondaryaddressline1', 'marketassociationaddress', 'addresstype2line1'],
        'SECONDARYADDRESSLINE2': ['secondaryaddress2','secondaryaddressline2', 'secondaryaddressline11', 'postaladdress2', 'postaladdressline2', 'postalcode2', 'secondaryaddressline2', 'custpermaddr2', 'secondaryaddressline2', 'addresstype2line2'],
        'SECONDARYADDRESSCITYLGA': ['secondaryaddresscitylga','citylga1'],
        'SECONDARYADDRESSSTATE' : ['secondaryaddressstate','state1', 'secondaryaddressstate', 'postaladdressline4','postalcode4','custpermstatecode', 'state1', 'addresstype2state' ],
        'SECONDARYADDRESSCOUNTRY' : ['secondaryaddresscountry','country1', 'cust_perm_cntry_code','address2country','postaladdress3','secondaryaddresscountry','seccountr'],
        'SECONDARYADDRESSPOSTCODE' : ['secondaryaddresspostcode','postcode','postalcodeofresaddr', 'postalcodeofresidenceaddress', 'postalcode', 'addresstype1postalcode', 'addresstype2postalcode', 'postaladdress', 'postalcodeofresidentialaddress', 'addresstype1postalcode', 'address1postcode', 'addresstype1postal'],
        'TAXID' : ['taxid','taxidentificationno', 'taxidentificationnumber', 'taxidentificationnum'],
        'PRIMARYPHONENUMBER' : ['primaryphonenumber','cellulartelephone', 'telephonenumber', 'phoneno', 'telephonenumber', 'officetelephone2', 'cellulartelno', 'officetelephone1', 'telephoneareacode', 'hometelephone', 'custcomuphonenum1', 'businessphone', 'phonetelephonenumber'],
        'SECONDARYPHONENUMBER' : ['secondaryphoneno','secondaryphonenumber','worktelephone', 'officetelephone2','mobileno','mobilephonenumber','worktelno', 'phonenumber', 'telephonenumber',  'mobilephone', 'secondaryphonenumber', 'workphone', 'custcomuphonenum2']
    }
credit_mapping = {
        'CUSTOMERID': ['customerid','customernumber','cusid','idno','custid','customeridind','customerkey','custcode','subjectidentificationnumber','customerno', 'customersid', 'idno', 'otheridnumber', 'customernumber','custno', 'customerkey', 'customeridorcustomernumber', 'subjectidno','subjectidentificationnum','subjectidentificationno','sheet1customerid'],
        'ACCOUNTNUMBER': ['accountnumber','accountno',  'loanno', 'currentacct', 'microcreditfacilityaccountnumber', 'acctnumloanno', 'foracid', 'facilityaccountnumber', 'accountnumber', 'microcreditfacilityaccountnumber', 'loanid', 'code', 'acctno', 'accountnoaccountid','acno','accountnum','acctnum'],
        'ACCOUNTSTATUS': ['accountstatus','creditstatus', 'statuscode', 'loanstatus','accounttypecode', 'custstatcode','schmcode', 'status','actstatus','acctstaus','acctstatus'],
        'ACCOUNTSTATUSDATE': ['accountstatusdate', 'statusdte', 'statusdate', 'accountstatusdate', 'custstatchgdate', 'statusdat', 'accountstatusdate','actstadate','statusdat','dateopened','consentstartdate','statusdays','accstatusdate'],
        'LOANEFFECTIVEDATE': ['loaneffectivedate','dateofloandisbursement','Date of Loan disbursement','dateofloan','dateloandisbursedloaneffectivedate','dateofloanfacilitydisbursementloaneffectivedate','loaneffectivedate','dateofdisbursement','disbursementdate','dateaccountopened','dateopened','firstdisbdt','opendate','dateacctopenned','dateofmortgagefacilityapproval','effectdate','startdate','accountactivationfirstdisbursementdate','startdate','dteaccountopened','dateaccountopened','accountactivationfirstdisbursementdate','dateofdisbursement','acctopndate','effectivedate','loaneffectivedate','accountactivationfirstdisbursementdate','disbutiondate','dateofcreditfacilityapproval','approvaldatedateoffirstdisbursement','approvaldate','issdate','issuedate','tdate','facilityapprovaldate','firstdisburmentdate'],
        'DEFEREDPAYMENTDATE':['DEFEREDPAYMENTDATE','deferedpaymentdate'],
        'CREDITLIMIT': ['creditlimit','creditlimitfacilityamountgloballimit','facilityamount','globallimit','openbalfirstdisbursementamt','amountgranted','openbalancecreditlimit','openingbalance','sanctlim','loanamountorcreditlimitforoverdraftaccounts','creditlimitfacilityamountgloballimit','currentbalance','amountequity'],
        'AVAILEDLIMIT': ['availedlimit','facilityamount','facilityamt','availedlimited','loanamount','loanfacilityamount','loanamountavailedlimit','loanfacilityamountavailedlimit','amountdisbursed','amountgranted','openingbalance','openbalance','loanfacilityamountavailedlimit','loanfacilityamount','approvedamt','amountdisbursedtilldate','approvedamount','openingbalance','amountgrantedcreditcardlimit','loanamountavailedlimit','principal','approvedamount','loanamt','amountapproved','loanamtloanamt','loanfacilityamountavailedlimit'],
        'OUTSTANDINGBALANCE': ['outstandingbalance','accountbalance','openingbalance','currentbalance','accountbal','balcurr','currentbal','principaloutstandingamount','outstandingprincipal','clrbalamt','trandatebal','currentoutstandingbalance','currentoutstanding','accountbalancecreditbalance','balance','totaloutstanding','acctbalance'],
        'CURRENTBALANCEDEBITIND':['currentbalancedebitind'],
        'INSTALMENTAMOUNT': ['instalmentamount','installmentamount','installamtprincipal','instalmentamt','installmentamountprincipal','totalinstallmentamount','installmentamount','instalmentamountn','installmentalamountprincipalpaidsofar'],
        'CURRENCY': ['curency','currencycode','currency','currcode','currengncy'],
        'DAYSINARREARS': ['daysinarrears','daysoverdue','monthsinarrears','dpdinmonths','montharrears','monthsarrears','daysoverdue','numberofdaysoverduemicrocreditfacility','daysinarrears','daysinarrears','numberofdaysoverduemicrocreditfacility','noofdaysoverdue','numberofdaysoverdue','daysareas','overduedaysprin'],
        'OVERDUEAMOUNT': ['overdueamount','overdueamtprn','amountoverdue','amountoverduearrearsamount','overdue'],
        'FACILITYTYPE': ['product','loantype','loanfacilitytype','accounttype','facilitytype','type','accounttypecode','typeofaccount','mortgagefacilitytype','customercategory','loanfacilitytype','transactiontypecode','schmtype','creditfacilitytype'],
        'FACILITYTENOR': ['loantenor','loanfacilitytenormonths','loan tenor','loanfacilitytenor','term','loan facility tenor','facility tenor','facilitytenor','FACILITYTENOR','LOAN (FACILITY) TENOR','LOAN DURATION','LOAN DURATION DAYS','LOAN_DURATION','TENORINDAYS','LOAN FACILITY TENOR','LOANDURATION','TERM','LOAN TENOR','LOAN DURATION (DAYS)','FACILITY TENOR','LOAN_TENOR','TENOR'],
        'FACILITYOWNERSHIPTYPE':['FACILITYOWNERSHIPTYPE'],
        'REPAYMENTFREQUENCY': ['repaymentfrequency','repayment frequency','REPAYMENTFREQUENCY','REPAYMENT FREQUENCY','REPAY FREQUENCY','FREQUENCY','REPAYMENT_FREQUENCY','REPAY_FREQ','PRINCIPAL REPAYMENT FREQUENCY','INTERESTFREQTYPE','INSTALLMENT_FREQUENCY','LR_FREQ_TYPE','RPYM_FREQ'],
        'LASTPAYMENTDATE': ['lastpaymentdate','last payment date','LASTPAYMENTDATE','LAST PAYMENT DATE','LAST PAYMENT RECEIVED DATE','DATE LAST PYMT WAS RCVD','PAYMENT DATE','LATEST_PAYMENT_DATE','LAST_TRANSACTION_DATE','LAST_PAYMT_DT_PRN','LAST_PAYMENT','LASTINTERESTPAIDDATE','DATE LATEST PAYMENT RECEIVED','LASTREPAYMENTDTE','LASTREPAYMENTDATE','LAST_PAYMENT_DATE','LAST_TRAN_DATE','DATE ON WHICH LAST PAYMENT WAS RECEIVED','LAST_DATE','LAST_INT_REC_DATE','LAST_INSTALMENT_DATE','DATELASTPAYMENTRECEIVED'],
        'LASTPAYMENTAMOUNT': ['lastpayamount','lastpaymentamount','last payment amount','LASTPAYMENTAMOUNT','LAST PAYMENT AMOUNT','LAST AMOUNT PAID','LAST PAYMENT RECEIVED','LASTPAYMENT','LAST_AMOUNT_PAID','LAST_AMT_RECVD_PRN','LAST_AMOUNT_RECEIVED','LASTTOTALPAYMENT','LASTREPAYMENTRECEIVED','LAST_PAYMENT_AMOUNT','LAST PAY AMOUNT','LAST PAYMENT AMOUNT RECEIVED','INSTALLMENT AMOUNT','LAST AMT PAYED','LAST_PAY_AMOUNT','PRINCIPAL PAID','LAST_AMT','LASTAMOUNTPAID'],
        'MATURITYDATE': ['maturitydate','maturity date','MATURITYDATE','MATURITY DATE','PLANNED CLOSURE DATE','CLOSE MATURITY DATE','MATURITY_DATE','EXPIRY_DATE','MATURITY_DT','MATURITY','PLANNED CLOSURE/MATURITY DATE','TERMINALDATE','PLANNED CLOSURE/ MATURITY DATE','CLOSED/ MATURITY DATE','MATURITYDTE','EI_PERD_END_DATE','LIM_EXP_DATE','EXPIRY DATE OR MATURITY DATE OF FACILITY','MICRO CREDIT FACILITY ACCOUNT CLOSING DATE','MATURITY DATE1','END DATE','PLANNED FINAL REPAYMENT DATE','MATUARITY DATE','MAT DATE','EXPIRES','MATDATE'],
        'INCOME':['INCOME','income'],
        'INCOMEFREQUENCY':['INCOMEFREQUENCY'],
        'OWNERTENANT':['OWNERTENANT'],
        'NUMBEROFPARTICIPANTSINJOINTLOAN':['NUMBEROFPARTICIPANTSINJOINTLOAN'],
        'DEPENDANTS':['DEPENDANTS'],
        'LOANCLASSIFICATION': ['loanclassification','loan classification','LOANCLASSIFICATION','LOAN CLASSIFICATION','ASSET_CLASS','CLASSIFICATION','ASSET CLASSIFICATION (AC)','ASSET CLASSIFICATION','LOAN_CLASSIFICATION','ASSET_CLASSIFICATION','LOAN_CLASS','ASSETCLASSIFICATION'],
        'LEGALCHALLENGESTATUS': ['legalchallengestatus','legal challenge status','LEGALCHALLENGESTATUS','LEGAL CHALLENGE STATUS','LEGAL_CHALLENGE_STATUS','LEGAL_STAT'],
        'LITIGATIONDATE': ['litigationdate','litigation date','LITIGATIONDATE','LITIGATION_DATE','LITIGATION DATE','LITIG_DATE'],
        'CONSENTSTATUS': ['consentstatu','consentstatus','consent status','CONSENTSTATUS','CONSENT STATUS','CONSENT_STATUS','CONS_STAT'],
        'LOANSECURITYSTATUS': ['loansecuritystatus','loan security status','LOANSECURITYSTATUS','LOAN SECURITY STATUS','LOAN_SECURITY_STATUS','SECU_STAT'],
        'COLLATERALTYPE': ['collateraltype','collateral type','COLLATERALTYPE','COLLATERAL TYPE','COLLATERAL_TYPE','COLAT_TYPE'],
        'COLLATERALDETAILS': ['collateraldetails','collateral details','COLLATERALDETAILS','COLLATERAL INFORMATION','COLLATERAL DETAILS','COLLATERAL_DETAILS','COLAT_DET'],
        'PREVIOUSACCOUNTNUMBER': ['previousaccountnumber','previous account number','PREVIOUSACCOUNTNUMBER','PREVIOUS ACCOUNT NUMBER','PREVIOUS_ACCOUNT_NO','MICRO CREDIT FACILITY PREVIOUS ACCOUNT NUMBER'],
        'PREVIOUSNAME': ['previousname','previous name','PREVIOUSNAME','PREVIOUSNAMEPREVIOUS NAME','PREVIOUS_NAME','PREVIOUS NAME'],
        'PREVIOUSCUSTOMERID': ['previouscustomerid','previous customer id','previous customerid','PREVIOUSCUSTOMERID','PREVIOUSCUSTOMERIDPREVIOUS CUSTOMER ID','PREVIOUS_CUSTOMER_ID','PREVIOUS CUSTOMER ID','SUBJECT PREVIOUS IDENTIFICATION NUMBER','PREV ID NO'],
        'PREVIOUSBRANCHCODE': ['previousbranchcode','previous branchcode','previous branch code','PREVIOUSBRANCHCODE','PREVIOUSBRANCHCODEPREVIOUS_BRANCH_CODE','PREVIOUS BRANCH CODE','DATA PROVIDER PREVIOUS BRANCH IDENTIFICATION NUMBER'],

    }
prin_mapping = {
        'CUSTOMERID': ['customerid','customer id','customerno','customer no','CUSTOMERID','CUSTOMER ID','CONSUMERID','CUSTOMER_NO','CUSTOMER_NUMBER','CUSTOMER_KEY','SUBJECT IDENTIFICATION NUMBER','CUSTCODE','CUSTOMER_ID','CUST_ID','CUSTOMER ID (OR CUSTOMER NUMBER)','ID NO','CUSTOMERS NUMBER','CUST_NO','SUBJECT ID NO','CUSTOMERIDCORP'],
        'PRINCIPALOFFICER1SURNAME': ['surname','fullname','principal officer1 surname','principalofficer1surname','principal officer 1 surname','PRINCIPALOFFICER1SURNAME','PRINCIPAL OFFICER 1 SURNAME','DIRECTOR_1_SURNAME','GUANRANTORS NAME','GUARANTORSNAME','PRINCIPAL OFFICER1SURNAME','PRINCIPAL OFFICER SURNAME','OFFICER99'],
        'PRINCIPALOFFICER1FIRSTNAME': ['firstname','principalofficer1firstname','principal officer 1 firstname','principal officer1 firstname','PRINCIPALOFFICER1FIRSTNAME','PRINCIPAL OFFICER 1 FIRSTNAME','DIRECTOR_1_FIRST_NAME','PRINCIPAL OFFICER1FIRSTNAME','PRINCIPAL OFFICER FIRSTNAME'],
        'PRINCIPALOFFICER1MIDDLENAME': ['middlename','othernames','principalofficer1middlename','principal officer 1 middle name','principal officer1 middlename','principal officer 1 middlename','PRINCIPALOFFICER1MIDDLENAME','PRINCIPAL OFFICER 1 MIDDLENAME','DIRECTOR_1_OTHER_NAMES','PRINCIPAL OFFICER1MIDDLENAME','PRINCIPAL OFFICER MIDDLENAME'],
        'PRINCIPALOFFICER1DATEOFBIRTH': ['PRINCIPALOFFICER1DATEOFBIRTH','dob','d o b','principalofficer1dateofbirth','principal officer 1 date of birth','principal officer1 date of birth','dateofbirth','date of birth','P1DATE OF BIRTH','DIRECTOR_1_BIRTH_DATE','NATIONAL ID','PRINCIPAL DATE OF BIRTH','PRINCIPAL_OFFICER2_DATE_OF_BIRTH','DATE OF BIRTH','DOB'],
        'PRINCIPALOFFICER1GENDER': ['PRINCIPALOFFICER1GENDER','principal officer 1 gender','principal officer1 gender','principalofficer1gender','gender','P1GENDER','GENDER','PRINCIPAL_OFFICER2_GENDER','PRINCIPAL OFFICER GENDER'],
        'PRINCIPALOFFICER1PRIMARYADDRESSLINE1': ['principalofficer1primaryaddressline1','principal officer1 primary address line1','principal officer 1 primary address line 1', 'primaryaddressline1','PRINCIPALOFFICER1PRIMARYADDRESSLINE1','GUANRANTORS ADDRESS 1','GUARANTORSADDRESS','PRINCIPAL PRIMARY ADDRESS LINE 1','PRINCIPAL OFFICER PRIMARY ADDRESS LINE 1','P_PRIMARY ADDRESS LINE 1','PRINCIPAL_OFFICER2_ADDRESS_LINE1','PRINCIPAL OFFICER PRIMARY ADDRESS LINE1','Primary Address Line 1'],
        'PRINCIPALOFFICER1PRIMARYADDRESSLINE2': ['principalofficer1primaryaddressline2','principal officer1 primary address line2','principal officer 1 primary address line 2', 'primary address line2','primaryaddressline2','PRINCIPALOFFICER1PRIMARYADDRESSLINE2','PRIMARY ADDRESS LINE 2','GUANRANTORS ADDRESS 2','PRINCIPAL PRIMARY ADDRESS LINE 2','PRINCIPAL OFFICER PRIMARY ADDRESS LINE 2','P_PRIMARY ADDRESS LINE 2','PRINCIPAL_OFFICER2_ADDRESS_LINE2','PRINCIPAL OFFICER PRIMARY ADDRESS LINE2','Primary Address Line 2'],
        'PRINCIPALOFFICER1CITY': ['citylga','principal officer1 city lga','principalofficer1citylga','principal officer 1 city','principal officer1 city','principalofficer1city','PRINCIPALOFFICER1CITY','city','GUANRANTORS ADDRESS 3','P_CITY','PRINCIPAL_OFFICER2_CITY','PRINCIPAL OFFICER CITY','city'],
        'PRINCIPALOFFICER1STATE': ['principalofficer1state','principal officer 1 state','principal officer1 state','state','PRINCIPALOFFICER1STATE','P_STATE','PRINCIPAL_OFFICER2_STATE','PRINCIPAL OFFICER STATE','State'],
        'PRINCIPALOFFICER1COUNTRY': ['principal officer 1 country','principal officer1 country','principalofficer1country','country','PRINCIPALOFFICER1COUNTRY','P_COUNTRY','PRINCIPAL_OFFICER2_COUNTRY','PRINCIPAL OFFICER COUNTRY'],
        'PRINCIPALOFFICER1NATIONALID': ['principal officer 1 national id','principal officer1 national id','principalofficer1nationalid','national id','nationalid','PRINCIPALOFFICER1NATIONALID','NATIONAL ID','DIRECTOR_1_NATIONAL_ID_NUMBER','PRINCIPAL_OFFICER2_NATIONAL_ID','nationalidentitynumber'],
        'PRINCIPALOFFICER1DRIVERSLICENSENUMBER': ['principal officer 1 drivers license no','principal officer1 drivers license no','principalofficer1driverslicenseno','drivers license no','driverslicenseno','PRINCIPALOFFICER1DRIVERSLICENSENUMBER','DRIVERS LICENSE NO','Drivers License Number 1','DIR1_DRIVERS_LICE_NUMBER','PRINCIPAL_OFFICER2_DRIVERS_LICENSE_NO','PRINCIPAL OFFICER DRIVER\'S LICENSE','driverslicensenumber'],
        'PRINCIPALOFFICER1BVNNUMBER': ['principal officer1 bvnno','principal officer1 bvn no','principal officer 1 bvn no','principalofficer1bvnno','bvn no','bvnno','PRINCIPALOFFICER1BVNNUMBER','BVN NO','BVNNO'],
        'PRINCIPALOFFICER1PASSPORTNUMBER': ['principal officer 1 passport no','PASSPORTNUMBER','principal officer1 passport no','principalofficer1passportno','passport no','passportno','PRINCIPALOFFICER1PASSPORTNUMBER','PASSPORT NO','DIRECTOR_1_PASSPORT_NUMBER'],
        'PRINCIPALOFFICER1OTHERIDNUMBER':['principalofficer1otheridnumber','principal officer 1 other id number','principal officer1 other id number'],
        'PRINCIPALOFFICER1PHONENUMBER': ['principal officer 1 phone number','principal officer1 phone number','principalofficer1phonenumber','phoneno','phone no','phone number','phonenumber','PRINCIPALOFFICER1PHONENUMBER','phone no 1','phone no1','phoneno1','PHONE NO1','GUANRANTORS TELEPHONE NUMBER','GUARANTORSTELEPHONENUMBER','PRINCIPAL OFFICER PHONE NO1'],
        'PRINCIPALOFFICER1EMAILADDRESS': ['principal officer 1 email address','principal officer1 email address','principalofficer1emailaddress','email','email address','emailaddress','PRINCIPALOFFICER1EMAILADDRESS','PRINCIPALOFFICER1EMAILADDRESSE','MAIL ADDRESS1','email','e-mail'],
        'PRINCIPALOFFICER1POSITIONINBUSINESS': ['principal officer1 position in business','principalofficer1positioninbusiness','position in business','positioninbusiness','PRINCIPALOFFICER1POSITIONINBUSINESS','POSITION IN BUSINESS'],
        'PRINCIPALOFFICER2SURNAME': ['principalofficer2surname','principal officer 2 surname','principal officer2 surname','PRINCIPALOFFICER2SURNAME','PRINCIPAL OFFICER 2 SURNAME','DIRECTOR_2_SURNAME','surname','PRINCIPAL OFFICER2 SURNAME 2','surname1'],
        'PRINCIPALOFFICER2FIRSTNAME': ['principalofficer2firstname','principal officer 2 firstname','principal officer2 firstname','PRINCIPALOFFICER2FIRSTNAME','PRINCIPAL OFFICER 2 FIRSTNAME','DIRECTOR_2_FIRST_NAME','PRINCIPAL OFFICER2 FIRSTNAME 2','firstname','firstname2'],
        'PRINCIPALOFFICER2MIDDLENAME': ['principal officer 2middlename','principal officer 2 middle name','principal officer2 middlename','PRINCIPALOFFICER2MIDDLENAME','principalofficer2middlename','DIRECTOR_2_OTHER_NAMES','PRINCIPAL OFFICER2 MIDDLENAME 2','middlename','othername','PRINCIPAL OFFICER 2 MIDDLE NAME'],
        'PRINCIPALOFFICER2DATEOFBIRTH': ['dateofbirth1','d o b1','dob1','principal officer2 date of birth','principalofficer2dateofbirth','date of birth1','PRINCIPALOFFICER2DATEOFBIRTH','P2DATE OF BIRTH','DIRECTOR_2_BIRTH_DATE','PRINCIPAL OFFICER DATE OF BIRTH','P_DATE OF BIRTH','PRINCIPAL OFFICER2 DATE OF BIRTH 2','DOB','date of birth','dateofbirth2'],
        'PRINCIPALOFFICER2GENDER': ['principal officer2 gender','gender','principalofficer2gender1','principalofficer2gender1','gender1','gender 1','PRINCIPALOFFICER2GENDER','P2GENDER','GENDER','PRINCIPAL OFFICER2 GENDER','gender2'],
        'PRINCIPALOFFICER2PRIMARYADDRESSLINE1': ['principal officer2 primary address line1','principalofficer2primaryaddressline1','primaryaddressline12','primary address line2','primaryaddressline2','primaryaddressline11','PRINCIPALOFFICER2PRIMARYADDRESSLINE1','P2PRIMARY ADDRESS LINE 1','P_PRIMARY ADDRESS LINE 1','P_ PRIMARY ADDRESS LINE 1','PRINCIPAL OFFICER PRIMARY ADDRESS LINE 1','PRINCIPAL OFFICER2 PRIMARY ADDRESS LINE1','primaryaddress2line1','primary address 2 line1'],
        'PRINCIPALOFFICER2PRIMARYADDRESSLINE2': ['principalofficer2 primary address line21','principalofficer2primaryaddressline2','primaryaddressline13','primaryaddressline14','principalofficer2primaryaddressline21','primary address line21','primaryaddressline21','PRINCIPALOFFICER2PRIMARYADDRESSLINE2','P2PRIMARY ADDRESS LINE 2','P_PRIMARY ADDRESS LINE 2','P_ PRIMARY ADDRESS LINE 2','PRINCIPAL OFFICER PRIMARY ADDRESS LINE 2','PRINCIPAL OFFICER2 PRIMARY ADDRESS LINE2','primaryaddress2line2'],
        'PRINCIPALOFFICER2CITY': ['citylga1','city1','principal officer2 city lga','principalofficer2citylga', 'principal officer2 city','principalofficer2city','principalofficer2city1', 'city1', 'PRINCIPALOFFICER2CITY','P2CITY','P_CITY','CITY','PRINCIPAL OFFICER2 CITY','LGA'],
        'PRINCIPALOFFICER2STATE': ['state1','principal officer2 state','principal officer2 state1','principalofficer2state','principalofficer2state1','state 1','P2STATE', 'STATE1_2', 'STATE11', 'P_CITY','PRINCIPALOFFICER2STATE'],
        'PRINCIPALOFFICER2COUNTRY': ['country1','principal officer2 country','principalofficer2country','principal officer2 country1','principalofficer2country1','country','PRINCIPALOFFICER2COUNTRY','P2COUNTRY','P_COUNTRY','PRINCIPAL OFFICER2 COUNTRY','country2','country.1'],
        'PRINCIPALOFFICER2NATIONALID': [ 'nationalid1', 'principal officer2 national id','principalofficer2nationalid','principalofficer2nationalid1', 'nationalid2',  'national id1', 'PRINCIPALOFFICER2NATIONALID', 'P2NATIONAL ID','DIRECTOR_2_NATIONAL_ID_NUMBER','P_NATIONAL ID','NATIONAL ID', 'PRINCIPAL OFFICER2 NATIONAL ID'],
        'PRINCIPALOFFICER2DRIVERSLISCENCENUMBER': ['principal officer2 drivers license no','driversliscenceno','principalofficer2driverslicenseno','principalofficer2driverslicenseno1','driverslicenseno1','drivers license no1','PRINCIPALOFFICER2DRIVERSLISCENCENUMBER','Drivers License Number 2','P2DRIVERS LISCENCE NO','DIRECTOR_2_DRVS_LICENCE_NUMBER','DRIVERS LICENSE NO','PRINCIPAL OFFICER2 DRIVERS LICENSE NO','driverslicensenumber2'],
        'PRINCIPALOFFICER2BVNNUMBER': ['bvnno1','principal officer2 bvn no','principalofficer2bvnno','principalofficer2bvnno1','bvn no1','PRINCIPALOFFICER2BVNNUMBER','P2BVN NO','BVN NO','PRINCIPAL OFFICER2 BVNNO'],
        'PRINCIPALOFFICER2PASSPORTNUMBER': ['principal officer2 passport no','principalofficer2passportno','passport no1','passportno1','PRINCIPALOFFICER2PASSPORTNUMBER','P2PASSPORT NO','DIRECTOR_2_PASSPORT_NUMBER','PASSPORT NO','PRINCIPAL OFFICER2 PASSPORT NO'],
        'PRINCIPALOFFICER2OTHERIDNUMBER':['principalofficer2otheridnumber','principal officer 2 other id number','principal officer2 other id number'],
        'PRINCIPALOFFICER2PHONENUMBER': ['phoneno11','principal officer2 phone number','principal officer2 phonenumber','principalofficer2phonenumber','principal officer2 phone no','principalofficer2phoneno','phonenumber11','phone number1','phonenumber11','phoneno11','phoneno1','phone no11','phoneno 11','PRINCIPALOFFICER2PHONENUMBER', 'P2PHONE NO1', 'PHONE NO 2','P_PHONE NO1','PRINCIPAL OFFICER2 PHONE NO1'],
        'PRINCIPALOFFICER2EMAILADDRESS': ['PRINCIPALOFFICER2EMAILADDRESS','principalofficer2emailaddress','emailaddress1','email address1','emailaddress1','P2EMAIL ADDRESS','E-MAIL ADDRESS1','PRINCIPAL OFFICER2 E MAIL ADDRESS','email1'],
        'PRINCIPALOFFICER2POSITIONINBUSINESS': ['positioninbusiness1','principal officer2 position in business','principalofficer2positioninbusiness','principalofficer2positioninbusiness1','position in business1''PRINCIPALOFFICER2POSITIONINBUSINESS','P2POSITION IN BUSINESS','PRINCIPAL OFFICER2 POSITION IN BUSINESS','Position In Business 2']
    }
guar_mapping = {
        'CUSTOMERSACCOUNTNUMBER': ['customers account no','customers accountno','customersaccountno','CUSTOMERSACCOUNTNUMBER', 'CUSTOMERS ACCOUNT NO.', 'ACCOUNT_NO', 'MICRO CREDIT FACILITY  ACCOUNT NUMBER1','loanaccount'],
        'GUARANTEESTATUSOFLOAN': ['guaranteestatusofloan','guarantee status of loan','GUARANTEESTATUSOFLOAN', 'GUARANTEE STATUS OF LOAN'],
        'TYPEOFGUARANTEE': ['typeofguarantee','type of guarantee','TYPEOFGUARANTEE', 'TYPE OF GUARANTEE'],
        'NAMEOFCORPORATEGUARANTOR': ['nameofcorporateguarantor','name of corporate guarantor','NAMEOFCORPORATEGUARANTOR', 'NAMEOFCORPORATEGUARANTOR'],
        'BIZIDNUMBEROFCORPORATEGUARANTOR': ['bizidnumberofcorporateguarantor','biz id number of corporate guarantor','BIZ ID NUMBER OF CORPORATE GUARANTOR'],
        'INDIVIDUALGUARANTORSURNAME': ['guarantorssurname','individualguarantorssurname','individual guarantors surname','INDIVIDUALGUARANTORSURNAME', 'INDIVIDUAL GUARANTORS SURNAME', 'GUARANTOR NAME', 'GUANRANTORS NAME', 'GUANRANTORS NAME 1', 'GUARANTORSNAME', 'GUARANTOR DETAILS', "INDIVIDUAL GUARANTOR'S SURNAME", 'GUARANTOR_1 SURNAME','guarantorsurname','Guarantor Surname'],
        'INDIVIDUALGUARANTORFIRSTNAME': ['guarantorsfirstname','individualguarantorsfirstname','individual guarantors firstname','INDIVIDUALGUARANTORFIRSTNAME', 'INDIVIDUAL GUARANTORS FIRST NAME', 'GUANRANTORS NAME 2', "INDIVIDUAL GUARANTOR'S FIRST NAME", 'GUARANTOR_1 FIRST NAME', 'GUARANTOR_1 OTHER NAME','guarantorfirstname','Guarantor FirstName'],
        'INDIVIDUALGUARNTORMIDDLENAME': ['guarntorsmiddlename','guarntorsothernames','individualguarntorsmiddlename','individual guarntors middlename','INDIVIDUALGUARNTORMIDDLENAME', 'INDIVIDUAL GUARNTORS MIDDLE NAME', "INDIVIDUAL GUARNTOR'S MIDDLE NAME", 'GUARANTOR_1 NATIONAL ID NUMBER','guarantormiddlename'],
        'GUARANTORDATEOFBIRTHINCORPORATION': ['birthday','birthdate','dateofincorporation','dateofbirth','guarantorsdateofbirth','guarantorsdateofbirthincorporation','guarantors date of birth incorporation','GUARANTORDATEOFBIRTHINCORPORATION', 'GUARANTORS DATE OF BIRTH/INCORPORATION', 'GUARANTORSADDRESS', "GUARANTOR'S DATE OF BIRTH/INCORPORATION"],
        'GUARANTORGENDER': ['guarantorsgender','guarantors gender','GUARANTORGENDER', 'GUARANTORS GENDER', "GUARANTOR'S GENDER"],
        'GUARANTORNATIONALIDNUMBER': ['guarantorsnationalid','guarantors national id','guarantors nationalid','GUARANTORNATIONALIDNUMBER', 'GUARANTORS NATIONAL ID', "GUARANTOR'S NATIONAL ID", "Guarantor's National ID",'Guarantor National Identity Number'],
        'GUARNATORINTLPASSPORTNUMBER': ['guarantorsintlpassportnumber','guarantors intl passport number','GUARNATORINTLPASSPORTNUMBER', 'GUARNATORS INTL PASSPORT NUMBER', "GUARANTOR'S INTL PASSPORT NUMBER", 'GUARANTOR_1 PASSPORT NUMBER'],
        'GUARANTORDRIVERSLICENCENUMBER': ['guarantorsdriverslicencenumber','guarantors drivers licencenumber','guarantors drivers licence number','GUARANTORDRIVERSLICENCENUMBER', 'GUARANTORS DRIVERS LICENCE NUMBER', "GUARANTOR'S DRIVERS LICENCE NUMBER", "GUARANTOR_1 DRIVER’S LICENCE NUMBER"],
        'GUARANTORBVN': ['guarantorsbvn','guarantors bvn','GUARANTORBVN', 'GUARANTORS BVN', "GUARANTOR'S BVN"],
        'GUARANTOROTHERID': ['guarantorsotherid','guarantors otherid','guarantors other id','GUARANTOROTHERID', 'GUARANTORS OTHER ID', "GUARANTOR'S OTHER ID", 'GUARANTOR_1 OTHER ID NUMBER'],
        'GUARANTORPRIMARYADDRESSLINE1': ['guarantorsprimaryaddressline1','guarantors primary address line 1','guarantors primary address line1','GUARANTORPRIMARYADDRESSLINE1', 'GUARANTORS PRIMARY ADDRESS LINE 1', 'GUARANTORS ADDRESS LINE 1', 'GUANRANTORS ADDRESS LINE 2', 'GUARANTOR ADDY 1', 'GUANRANTORS ADDRESS 1', "GUARANTOR'S PRIMARY ADDRESS LINE 1", 'GUARANTOR_1 ADDRESS LINE1'],
        'GUARANTORPRIMARYADDRESSLINE2': ['guarantorsprimaryaddressline2','guarantors primary address line 2','guarantors primary address line2','GUARANTORPRIMARYADDRESSLINE2', 'GUARANTORS PRIMARY ADDRESS LINE 2', 'GUARANTORS ADDRESS LINE 2', 'GUANRANTORS ADDRESS LINE 21', 'GUARANTOR ADDY 2', 'GUANRANTORS ADDRESS 2', "GUARANTOR'S PRIMARY ADDRESS LINE 2", 'GUARANTOR_1 ADDRESS LINE2'],
        'GUARANTORPRIMARYADDRESSCITYLGA': ['guarantorsprimaryaddresscitylga','guarantors primary address city lga','guarantors primary address citylga','GUARANTORPRIMARYADDRESSCITYLGA', 'GUARANTORS PRIMARY ADDRESS CITY/LGA', 'GUARANTORS ADDRESS LINE 3', 'GUANRANTORS ADDRESS LINE 3', 'GUARANTOR ADDY 3', 'GUANRANTORS ADDRESS 3', "GUARANTOR'S PRIMARY ADDRESS CITY/LGA", 'GUARANTOR_1 ADDRESS LINE3'],
        'GUARANTORPRIMARYADDRESSSTATE': ['guarantorsprimarystate','guarantors primarystate','guarantors primary state','GUARANTORPRIMARYADDRESSSTATE', 'GUARANTORS PRIMARY STATE', "GUARANTOR'S PRIMARY STATE",'GUARANTORSTATE'],
        'GUARANTORPRIMARYADDRESSCOUNTRY': ['guarantorscountry','guarantorsprimarycountry','guarantors primary country','GUARANTORPRIMARYADDRESSCOUNTRY', 'GUARANTORS PRIMARY COUNTRY', "GUARANTOR'S PRIMARY COUNTRY"],
        'GUARANTORPRIMARYPHONENUMBER': ['guarantorsprimaryphonenumber','guarantors primary phonenumber','guarantors primary phone number','GUARANTORPRIMARYPHONENUMBER', 'GUARANTORS PRIMARY PHONE NUMBER', 'GUARANTORS TELEPHONE NUMBER', 'GUANRANTORS TELEPHONE NUMBER', 'GUARANTOR PHONE', 'GUARANTORSTELEPHONENUMBER', "GUARANTOR'S PRIMARY PHONE NUMBER"],
        'GUARANTOREMAIL': ['guarantorsemailaddress','guarantors email','guarantorsemail','guarantors email address','GUARANTOREMAIL', 'GUARANTORS E-MAIL ADDRESS', "GUARANTOR'S EMAIL ADDRESS"],
        'FILLER':['FILLER','filler']
    }
Gender_dict = {"001":[ "Male", "male","M", "m",'001','01','1','mal'],
               "002":["female",'002',"f",'02','2','femal']}
Country_dict = {
    "NG": ["ng", "nigerian", "nigeria", "naija", "ngr", "ngn"],
    "AD": ["andorra", "ad"],
    "AE": ["united arab emirates", "uae", "ae"],
    "AF": ["afghanistan", "AF"],
    "AG": ["antigua and barbuda", "ag"],
    "AI": ["anguilla", "ai"],
    "AL": ["albania", "al"],
    "AM": ["armenia", "am"],
    "AN": ["netherlands antilles", "an"],
    "AO": ["angola", "ao"],
    "AQ": ["antarctica", "aq"],
    "AR": ["argentina", "ar"],
    "AS": ["american samoa", "as"],
    "AT": ["austria", "at"],
    "AU": ["australia", "au"],
    "AW": ["aruba", "aw"],
    "AX": ["aland Islands", "ax"],
    "AZ": ["azerbaijan", "az"],
    "BA": ["bosnia and herzegovina", "ba"],
    "BB": ["barbados", "bb"],
    "BD": ["bangladesh", "bd"],
    "BE": ["belgium", "be"],
    "BF": ["burkina faso", "bf"],
    "BG": ["bulgaria", "bg"],
    "BH": ["Bahrain", "bh"],
    "BI": ["burundi", "bi"],
    "BJ": ["benin", "bj"],
    "BL": ["saint barthélemy", "bl"],
    "BM": ["Bermuda", "BM"],
    "BN": ["brunei darussalam", "bn"],
    "BO": ["bolivia", "bo"],
    "BR": ["brazil", "br"],
    "BS": ["bahamas", "bs"],
    "BT": ["bhutan", "bt"],
    "BV": ["bouvet island", "bv"],
    "BW": ["botswana", "bw"],
    "BY": ["belarus", "by"],
    "BZ": ["belize", "bz"],
    "CA": ["canada", "ca"],
    "CC": ["cocos keeling islands", "cc"],
    "CD": ["congo the democratic republic of the", "cd"],
    "CF": ["central african republic", "cf"],
    "CG": ["congo", "cg"],
    "CH": ["switzerland", "ch"],
    "CI": ["côte divoire", "ci"],
    "CK": ["cook islands", "ck"],
    "CL": ["chile", "cl"],
    "CM": ["cameroon", "cm"],
    "CN": ["china", "cn"],
    "CO": ["colombia", "co"],
    "CR": ["costa rica", "cr"],
    "CU": ["cuba", "cu"],
    "CV": ["cape verde", "cv"],
    "CX": ["christmas island", "cx"],
    "CY": ["cyprus", "cy"],
    "CZ": ["czech republic", "cz"],
    "DE": ["germany", "de"],
    "DJ": ["djibouti", "dj"],
    "DK": ["denmark", "dk"],
    "DM": ["dominica", "dm"],
    "DO": ["dominican republic", "do"],
    "DZ": ["algeria", "dz"],
    "EC": ["ecuador", "ec"],
    "EE": ["estonia", "ee"],
    "EG": ["egypt", "eg"],
    "EH": ["western sahara", "eh"],
    "ER": ["eritrea", "er"],
    "ES": ["spain", "es"],
    "ET": ["ethiopia", "et"],
    "FI": ["finland", "fi"],
    "FJ": ["fiji", "FJ"],
    "FK": ["falkland islands Malvinas", "fk"],
    "FM": ["micronesia, federated states of", "fm"],
    "FO": ["faroe islands", "fo"],
    "FR": ["france", "fr"],
    "GA": ["gabon", "ga"],
    "Gb": ["united kingdom", "gb"],
    "GD": ["grenada", "gd"],
    "GE": ["Georgia", "ge"],
    "GF": ["french guiana", "gf"],
    "GG": ["guernsey", "gg"],
    "GH": ["ghana", "gh"],
    "GI": ["gibraltar", "gi"],
    "GL": ["greenland", "gl"],
    "GM": ["gambia", "gm"],
    "GN": ["guinea", "gn"],
    "GP": ["guadeloupe", "gp"],
    "GQ": ["equatorial guinea", "gq"],
    "GR": ["greece", "gr"],
    "GS": ["south georgia and the south sandwich islands", "gs"],
    "GT": ["guatemala", "gt"],
    "GU": ["guam", "gu"],
    "GW": ["guineabissau", "gw"],
    "GY": ["guyana", "gy"],
    "HK": ["hong kong", "hk"],
    "HM": ["heard island and mcdonald islands", "hm"],
    "HN": ["honduras", "hn"],
    "HR": ["croatia", "hr"],
    "HT": ["haiti", "ht"],
    "HU": ["hungary", "hu"],
    "ID": ["indonesia", "id"],
    "IE": ["ireland", "ie"],
    "IL": ["israel", "il"],
    "IM": ["isle of man", "im"],
    "IN": ["india", "in"],
    "IO": ["british indian ocean territory", "io"],
    "IQ": ["iraq", "iq"],
    "IR": ["iran islamic republic of", "ir"],
    "IS": ["iceland", "is"],
    "IT": ["italy", "it"],
    "JE": ["jersey", "je"],
    "JM": ["jamaica", "jm"],
    "JO": ["jordan", "jo"],
    "JP": ["japan", "jp"],
    "KE": ["kenya", "ke"],
    "KG": ["kyrgyzstan", "kg"],
    "KH": ["cambodia", "kh"],
    "KI": ["kiribati", "ki"],
    "KM": ["comoros", "km"],
    "KN": ["saint kitts and nevis", "kn"],
    "KP": ["korea democratic peoples republic of", "kp"],
    "KR": ["korea republic of", "kr"],
    "KW": ["kuwait", "kw"],
    "KY": ["cayman islands", "ky"],
    "KZ": ["kazakhstan", "kz"],
    "LA": ["lao peoples democratic republic", "la"],
    "LB": ["lebanon", "lb"],
    "LC": ["saint lucia", "lc"],
    "LI": ["liechtenstein", "li"],
    "LK": ["sri lanka", "lk"],
    "LR": ["liberia", "lr"],
    "LS": ["lesotho", "ls"],
    "LT": ["lithuania", "lt"],
    "LU": ["luxembourg", "lu"],
    "LV": ["latvia", "lv"],
    "LY": ["libyan arab jamahiriya", "ly"],
    "MA": ["morocco", "ma"],
    "MC": ["monaco", "mc"],
    "MD": ["moldova republic of", "md"],
    "ME": ["montenegro", "me"],
    "MF": ["saint martin", "mf"],
    "MG": ["madagascar", "mg"],
    "MH": ["marshall islands", "mh"],
    "MK": ["macedonia the former yugoslav republic of", "mk"],
    "ML": ["mali", "ml"],
    "MM": ["myanmar", "mm"],
    "MN": ["mongolia", "mn"],
    "MO": ["macao", "mo"],
    "MP": ["northern mariana islands", "mp"],
    "MQ": ["martinique", "mq"],
    "MR": ["mauritania", "mr"],
    "MS": ["montserrat", "ms"],
    "MT": ["malta", "mt"],
    "MU": ["mauritius", "mu"],
    "MV": ["maldives", "mv"],
    "MW": ["malawi", "mw"],
    "MX": ["mexico", "mx"],
    "MY": ["malaysia", "my"],
    "MZ": ["mozambique", "mz"],
    "NA": ["namibia", "na"],
    "NC": ["new caledonia", "nc"],
    "NE": ["niger", "ne"],
    "NF": ["norfolk island", "nf"],
    "NI": ["nicaragua", "ni"],
    "NL": ["netherlands", "nl"],
    "NO": ["norway", "no"],
    "NP": ["nepal", "np"],
    "NR": ["nauru", "nr"],
    "NU": ["niue", "nu"],
    "NZ": ["new zealand", "nz"],
    "OM": ["oman", "om"],
    "PA": ["panama", "pa"],
    "PE": ["peru", "pe"],
    "PF": ["french polynesia", "pf"],
    "PG": ["papua new guinea", "pg"],
    "PH": ["philippines", "ph"],
    "PK": ["pakistan", "pk"],
    "PL": ["poland", "pl"],
    "PM": ["saint pierre and miquelon", "pm"],
    "PN": ["pitcairn", "pn"],
    "PR": ["puerto rico", "pr"],
    "PS": ["palestinian territory, occupied", "ps"],
    "PT": ["portugal", "pt"],
    "PW": ["palau", "pw"],
    "PY": ["paraguay", "py"],
    "QA": ["qatar", "qa"],
    "RE": ["réunion", "re"],
    "RO": ["romania", "ro"],
    "RS": ["serbia", "rs"],
    "RU": ["russian federation", "ru"],
    "RW": ["rwanda", "rw"],
    "SA": ["saudi arabia", "sa"],
    "SB": ["solomon islands", "sb"],
    "SC": ["seychelles", "sc"],
    "SD": ["sudan", "sd"],
    "SE": ["sweden", "se"],
    "SG": ["singapore", "sg"],
    "SH": ["saint helena", "sh"],
    "SI": ["slovenia", "si"],
    "SJ": ["svalbard and jan mayen", "sj"],
    "SK": ["slovakia", "sk"],
    "SL": ["sierra leone", "sl"],
    "SM": ["san marino", "sm"],
    "SN": ["senegal", "sn"],
    "SO": ["somalia", "so"],
    "SR": ["suriname", "sr"],
    "ST": ["são tome and príncipe", "st"],
    "SV": ["el salvador", "sv"],
    "SY": ["syrian arab republic", "sy"],
    "SZ": ["swaziland", "sz"],
    "TC": ["turks and caicos islands", "tc"],
    "TD": ["chad", "td"],
    "TF": ["french southern territories", "tf"],
    "TG": ["togo", "tg"],
    "TH": ["thailand", "th"],
    "TJ": ["tajikistan", "tj"],
    "TK": ["tokelau", "tk"],
    "TL": ["timor-leste", "tl"],
    "TM": ["turkmenistan", "tm"],
    "TN": ["tunisia", "tn"],
    "TO": ["tonga", "to"],
    "TR": ["turkey", "tr"],
    "TT": ["trinidad and tobago", "tt"],
    "TV": ["tuvalu", "tv"],
    "TW": ["taiwan, province of china", "tw"],
    "TZ": ["tanzania, united republic of", "tz"],
    "UA": ["ukraine", "ua"],
    "UG": ["uganda", "ug"],
    "UM": ["united states minor outlying islands", "um"],
    "US": ["united states of america", "us"],
    "UY": ["uruguay", "uy"],
    "UZ": ["uzbekistan", "uz"],
    "VA": ["holy see vatican city state", "va"],
    "VC": ["saint vincent and the grenadines", "vc"],
    "VE": ["venezuela", "ve"],
    "VG": ["virgin islands, british", "vg"],
    "VI": ["virgin islands us", "vi"],
    "VN": ["viet nam", "vn"],
    "VU": ["vanuatu", "vu"],
    "WF": ["wallis and futuna", "wf"],
    "WS": ["samoa", "ws"],
    "YE": ["yemen", "ye"],
    "YT": ["mayotte", "yt"],
    "ZA": ["south africa", "za"],
    "ZM": ["zambia", "zm"],
    "ZW": ["zimbabwe", "zw"]
                }

Marital_dict = {
    'Married': ['m', 'married', 'marry'],
    'Single': ['single', 's'],
    'Widower': ['wr', 'widower'],
    'Widow': ['wd', 'widow'],
    'Divorced': ['d', 'divorced']
}
Borrower_dict = {
    'I': ['individual', 'i'],
    'J': ['joint', 'j'],
    'G': ['group', 'g']
}
Employer_dict = {
    'UE': ['unemployed', 'ue'],
    'E': ['employed', 'e'],
    'SE': ['selfemployed', 'self employed', 'se']
}
Title_dict = {
    'Mister': ['mr', 'mister'],
    'Mrs': ['mrs'],
    'Miss/Mrs': ['ms', 'missmrs'],
    'Miss': ['miss'],
    'Captain': ['captain', 'capt'],
    'Colonel': ['colonel', 'col'],
    'Doctor': ['doctor', 'dr', 'doc'],
    'Lady': ['lady'],
    'Lieutenant': ['lieutenant', 'lt'],
    'Major': ['major', 'maj'],
    'Pastor': ['pastor', 'pst', 'ps'],
    'Professor': ['professor', 'prof'],
    'Reverend': ['reverend', 'rev'],
    'Sergeant': ['sergeant', 'sgt'],
    'Sir': ['sir'],
    'His Excellency': ['he', 'his excellency'],
    'Justice': ['justice', 'judg'],
    'Chief': ['chief', 'chf'],
    'Alhaji': ['alhaji', 'alhj'],
    'Apostle': ['apostle', 'apos'],
    'Commander': ['commander', 'cdr'],
    'Bishop': ['bishop', 'bish'],
    'Flight Lieutenant': ['flight lieutenant', 'flt'],
    'Barrister (Lawyer)': ['barrister lawyer', 'barr'],
    'Major General': ['major general', 'mgen'],
    'General': ['general', 'gen'],
    'Honourable': ['honourable', 'hon'],
    'Engineer': ['engineer', 'engr']
}
Occu_dict = {"Agriculture": ["3000", "agriculture"],
             "Food Crops (Grains) – Distribution": ["3001", "food crops (grains) – distribution"],
             "Forestry": ["3002", "forestry"],
             "Fishing": ["3003", "fishing"],
             "Agricultural – Others": ["3004", "agriculturalothers"],
             "Food Crops (Grains) – Production": ["3005", "foodcropsgrainsproduction"],
             "Food Crops (Other) e.g. Tuber, Citrus": ["3006", "foodcropsotheregtubercitrus"],
             "Cash Crops (Cotton, cocoa, Palm Produce, Groundnuts, Oil Seeds, Rubber, Tobacco)": ["3007", "cashcropscottoncocoapalmproducegroundnutsoilseedsrubbertobacco"],
             "Poultry": ["3008", "poultry"],
             "Other Livestock": ["3009", "otherlivestock"],
             "Food Crops (Grains)": ["3010", "foodcropsgrains"],
             "Transportation": ["3800", "transportation"],
             "Transportation – Rail Transport": ["3801", "transportationrailtransport"],
             "Transportation – Road Transport": ["3802", "transportationroadtransport"],
             "Transportation – Water Transport": ["3803", "transportationwatertransport"],
             "Transportation – Air Transport": ["3804", "transportationairtransport"],
             "Government/ Other Organizations": ["6000", "governmentotherorganizations"],
             "Government – Others": ["6040", "governmentothers"],
             "Statutory Boards & Corporations": ["6080", "statutoryboardscorporations"],
             "Government-Owned Companies": ["6090", "governmentownedcompanies"],
             "Federal Government": ["6101", "federalgovernment"],
             "State Government": ["6102", "stategovernment"],
             "Local Government": ["6103", "localgovernment"],
             "Parastatals": ["6030", "parastatals"],
             "Manufacturing": ["3200", "manufacturing"],
             "Manufacturing – Flour Milling & Bakeries": ["3201", "manufacturingflourmillingbakeries"],
             "Manufacturing – Meat & Other Food Processing, Canning & Cold Storage": ["3202", "manufacturingmeatotherfoodprocessingcanningcoldstorage"],
             "Manufacturing – Beverages": ["3203", "beverages","manufacturingbeverages"],
             "Manufacturing – Textile & Apparel": ["3204", "manufacturingtextileapparel"],
             "Manufacturing – Footwear (Excluding Rubber Footwear)": ["3205", "manufacturingfootwearexcludingrubberfootwear"],
             "Manufacturing – Wood Products (Including Furniture)": ["3206", "manufacturingwoodproductsincludingfurniture"],
             "Manufacturing – Paper & Paper Products": ["3207", "manufacturingpaperpaperproducts"],
             "Manufacturing – Printing, Publishing": ["3208", "printingpublishing","manufacturingprintingpublishing"],
             "Manufacturing – Rubber Products (Including Rubber Footwear)": ["3209", "manufacturingrubberproductsincludingrubberfootwear"],
             "Manufacturing – Soaps, Oils & Detergents": ["3210", "manufacturingsoapsoilsdetergents"],
             "Manufacturing – Petroleum & Coal Products": ["3211", "manufacturingpetroleumcoalproducts"],
             "Manufacturing – Building Materials, Pottery, Ceramics & Glass": ["3212", "manufacturingbuildingmaterialspotteryceramicsglass"],
             "Manufacturing – Basic Metal Products": ["3213", "manufacturingbasicmetalproducts"],
             "Manufacturing – Miscellaneous Manufacturing & Processing": ["3214", "manufacturingmiscellaneousmanufacturingprocessing"],
             "Manufacturing – Other Non Metallic Products": ["3215", "manufacturing – other non metallic products"],
             "Manufacturing – Breweries": ["3216", "breweries","manufacturingbreweries"],
             "Manufacturing – Tobacco": ["3217", "manufacturingtobacco"],
             "Industrial Products, Machinery, Raw Materials": ["3517", "industrialproductsmachineryrawmaterials"],
             "Textiles, Apparels, Footwear": ["3519", "textiles","footwear","apparels","apparel","textilesapparelsfootwear"],
             "Mining and Quarrying": ["3100", "miningandquarrying"],
             "Coal Mining": ["3101", "coalmining"],
             "Metallic Mining (Tin, Ore, Iron, Zinc & Lead)": ["3103", "metallicminingtinoreironzinclead"],
             "Other Non-Metallic Mining (Including Quarrying and Sand pits)": ["3104", "othernonmetallicminingincludingquarryingandsandpits)"],
             "Consumer Durables": ["3512", "consumerdurables"],
             "Consumer Food Products": ["3513", "consumerfoodproducts"],
             "Imports And Domestic Trade": ["3514", "importsanddomestictrade"],
             "Industrial Food Products": ["3515", "industrialfoodproducts"],
             "Soaps, Oils, Detergents, Chemicals": ["3516","soaps","Chemical","Chemicals","oils","detergents", "soapsoilsdetergentschemicals"],
             "Merchants": ["3550","merchant" "merchants"],
             "Conglomerates": ["3551","conglomerate", "conglomerates"],
             "Retail Merchants": ["3552", "retailmerchant","retailmerchants"],
             "Wholesale Merchants": ["3553", "wholesalemerchant","wholesalemerchants"],
             "General Commerce": ["3500", "generalcommerce"],
             "Cocoa Export": ["3501", "cocoaexport"],
             "Groundnut, Groundnut Oil Export": ["3502","groundnut", "groundnutoilexport","groundnutgroundnutoilexport"],
             "Palm Produce Export": ["3503", "palmproduceexport"],
             "Cotton Export": ["3504", "cotton export"],
             "Hides & Skin Export": ["3505", "hidesskinexport"],
             "Rubber Products Exports": ["3506", "rubberproductsexports"],
             "Timber Products Exports": ["3507", "timberproductsexports"],
             "Other Agricultural Exports": ["3508", "otheragriculturalexports"],
             "Others": ["3509", "others"],
             "Non-Agricultural Exports": ["3518", "nonagriculturalexports"],
             "Legal Firms": ["5305","legalfirm", "legalfirms","lawyer"],
             "Management Consultants": ["5306", "managementconsultants"],
             "Personal": ["5307", "personal"],
             "Personal And Professional": ["5308", "personalandprofessional"],
             "Personal/ Professional": ['5300','personalprofessional'],
             "Auditors, Accountants, Receivers,Managers": ["5301","auditor", "auditors","accountants","receivers","managers","manager","auditorsaccountantsreceiversmanagers"],
             "Doctors (Traditional Orthodox)": ["5302","traditionalorthodox", "doctorstraditionalorthodox"],
             "Engineers": ["5303", "engineers"],
             "Finance and Insurance": ["4000", "financeandinsurance"],
             "Insurance Companies": ["4020", "insurancecompany","insurancecompanies"],
             "Finance Houses": ["4030", "financehouse","financehouses"],
             "Commercial Banks": ["4501", "commercialbank","commercialbanks"],
             "Merchant Banks": ["4502","merchantbank", "merchantbanks"],
             "Discount Houses": ["4503", "discounthouse","discounthouses"],
             "Other Financial Institutions": ["4504", "otherfinancialinstitutions"],
             "Hire Purchase & Leasing Companies": ["4505","hirepurchase","leasingcompany", "leasingcompanies","hirepurchaseleasingcompanies"],
             "Building Societies, Finance Co-operatives": ["4506","financecooperatives","financecooperative", "buildingsocieties","buildingsociety","buildingsocietiesfinancecooperatives"],
             "Communications – Other Communications": ["3805","communications","communication", "communicationsothercommunications"],
             "Hospitals, Medical Centres, Dental Clinics": ["3054","hospital","hospitals","medicalcentres","medicalcentre","medicalcenter","dentalclinics","dentalclinic", "hospitalsmedicalcentresdentalclinics"],
             "Travel Agencies, Shipping Agencies": ["3059", "travelagencies","travelagency","shippingagencies","shippingagency","travelagenciesshippingagencies"],
             "Hotels, Restaurants": ["3055", "restaurants","restaurant","hotels","hotel","hotelsrestaurants"],
             "Automobiles, Automobile Products": ["3510","automobiles","automobile","automobileproducts", "automobilesautomobileproducts"],
             "Universities": ["6020","university", "universities"],
             "Schools, Educational Institutions": ["3058","school","schools", "educationalinstitutions","educationalinstitution","schoolseducationalinstitutions"],
             "Crude Petroleum & Gas": ["3102", "petroleum","gas","crudepetroleumgas"],
             "General": ["3050", "general"],
             "Advertising Agencies": ["3051","advertising","advertisingagency", "advertisingagencies"],
             "Computer Software, Hardware": ["3052","computersoftware", "computersoftwarehardware"],
             "Dry Cleaners, Cleaning Agencies": ["3053","drycleaners", "drycleanerscleaningagencies"],
             "Mechanics, Auto Repair Workshops": ["3056","mechanic", "mechanicsautorepairworkshops"],
             "Other Miscellaneous Advances": ["3057", "other miscellaneous advances"],
             "Fashion Designers": ["5304", "fashiondesigner","fashiondesigners"],
             "Commodity Boards": ["6010","commodityboard" "commodityboards"],
             'Banker':['003','03','3','banker'],
             'Business':['004','04','4','business'],
             'CIVIL SERVANT':['008','08','8','civilservant'],
             'Lawyer':['022','22','lawyer'],
             'Administrator':['001','01','1','administrator'],
             'Chartered Accountant':['006','06','6','charteredaccountant'],
             'Cleric':['009','09','9','cleric'],
             'Consultant':['011','11','consultant'],
             'Doctor':['doctor','012','12'],
             'Engineer':['engineer','014','14'],
             'Farmer':['farmer','016','16'],
             'IT Professional':['20','020','itprofessional'],
             'Nursing':['026','nursing','26'],
             'Pilot':['pilot','028','28'],
             'Service':['service','033','33'],
             'Teacher':['teacher','035','35'],
             'Others':['other','036','36']
             }
state_dict = {'001': ['abia', 'abia state','1','01','001'],
              '002': ['Adamawa','adamawa state','2','02','002' ],
              '003': ['akwaibom state', 'akwaibom', '3','03','003'],
              '004': ['anambra', 'anambra State','4','04', '004'],
              '005': ['bauchi', 'bauchi state', '5','05', '005'],
              '006': ['bayelsa','bayelsa state', '6','06','006'],
              '007': ['benue','benue state','7','07', '007'],
              '008': ['borno','borno State', '8','08','008'],
              '009': ['crossriver','crossriver state',  '9','09','009'],
              '010': ['delta', 'delta state', '10','010'],
              '011': ['ebonyi','ebonyi state','11', '011'],
              '012': ['edo','edo state', '12','012'],
              '013': ['ekiti', 'ekiti state', '13', '013'],
                '014': ['enugu', 'enugu state', '14', '014'],
                '015': ['federal capital territory', 'fct', '15', '015','abuja','abuja fct'],
                '016': ['gombe', 'gombe state', '16', '016'],
                '017': ['imo', 'imo state', '17', '017'],
                '018': ['jigawa', 'jigawa state', '18', '018'],
                '019': ['kaduna', 'kaduna state', '19', '019'],
                '020': ['kano', 'kano state', '20', '020'],
                '021': ['katsina', 'katsina state', '21', '021'],
                '022': ['kebbi', 'kebbi state', '22', '022'],
                '023': ['kogi', 'kogi state', '23', '023'],
                '024': ['kwara', 'kwara state', '24', '024'],
                '025': ['lagos', 'lagos state', '25', '025'],
                '026': ['nasarawa', 'nasarawa state', '26', '026'],
                '027': ['niger', 'niger state', '27', '027'],
                '028': ['ogun', 'ogun state', '28', '028'],
                '029': ['ondo', 'ondo state', '29', '029'],
                '030': ['osun', 'osun state', '30', '030'],
                '031': ['oyo', 'oyo state', '31', '031'],
                '032': ['plateau', 'plateau state', '32', '032'],
                '033': ['rivers', 'rivers state', '33', '033'],
                '034': ['sokoto', 'sokoto state', '34', '034'],
                '035': ['taraba', 'taraba state', '35', '035'],
                '036': ['yobe', 'yobe state', '36', '036'],
                '037': ['zamfara', 'zamfara state', '37', '037']
             }

sec_dict = {
    "Agriculture/Forestry": ["1",'01','001','agriculture','forestry', "agricultureforestry"],
    "Building/Construction/Real Estate development": ["2", '02','002','building','construction','realestate','realestatedevelopment',"buildingconstructionrealestatedevelopment"],
    "Transportation/Storage": ["3",'03','003','transportation','storage', "transportationstorage"],
    "Government/MDAs": ["4",'04','004','government','mdas', "governmentmdas"],
    "Manufacturing/Producing": ["5",'05','005','manufacturing','producing', "manufacturingproducing"],
    "Mning/Quarrying/Mineral business": ["6",'06','006','mining','quarrying','mineral','mineralbusiness', "miningquarryingmineralbusiness"],
    "Consumer durables/household items": ["7",'07','007','consumerdurables','householditems', "consumerdurableshouseholditems"],
    "General Commerce/Traders/Importers/Exporters": ["8",'08','008','generalcommerce','traders','importers', "generalcommercetradersimportersexporters",'generalcommercetrading'],
    "Professionals - Journalists/Lawyers/Accountants etc.": ["9",'09','009','journalists','journalist','lawyers','lawyer','accountants','accountant', "professionalsjournalistslawyersaccountantsetc"],
    "Financial Services/banking/Insurance/capital Markets": ["10",'010','capitalmarkets','capitalmarket','financialservices','financialservice','banking','insurance', "financialservicesbankinginsurancecapitalmarkets"],
    "Communications/Tele-communications": ["11",'011','communications','communication','telecommunications','telecommunication', "communicationstelecommunications"],
    "Hospitals/Healthcare/Pharmaceuticals": ["12",'012','hospitals', 'hospital','healthcare','pharmaceutical','pharmaceuticals',"hospitalshealthcarepharmaceuticals"],
    "Hotels/Hospitality/Leisure": ["13",'013','hotels','hotel','hospitality','leisure', "hotelshospitalityleisure"],
    "Automobiles/Automobile Products": ["14",'014','automobiles','automobileproducts','automobileproduct', "automobilesautomobileproducts"],
    "Education/Schools": ["15",'015','education','schools','school', "educationschools"],
    "Oil & Gas": ["16",'016','oil','gas', "oilandgas"],
    "Power/Energy": ["17",'017','power','energy', "powerenergy"],
    "Water supply, sewage, waste management": ["18",'018','watersupply','sewage','wastemanagement', "watersupplysewagewastemanagement"],
    "Arts/entertainment": ["19",'019', 'arts','entertainment',"artsentertainment"],
    "Activities of extra-territorial organizations and bodies": ["20",'020', "activitiesofextraterritorialorganizationsandbodies"],
    "Military/Law Enforcement": ["21",'021','military','lawenforcement', "militarylawenforcement"],
    "Religious services": ["22",'022','religious', "religiousservices"],
    "Others/Miscelaneous": ["23",'023','others','miscellaneous', "othersmiscellaneous"]
}

Currency_dict = {"NGN": ["naira","n", "ng","ngn"],
                 "GBP": ["pounds", "gbp"],
                 "USD": ["dollars", "usd", "usdollars","dollar"],
                 "AFN": ["afn"],
                 "EUR": ["eur"],
                 "ALL": ["all"],
                 "DZD": ["dzd"],
                 "AOA": ["aoa"],
                 "XCD": ["xcd"],
                 "ARS": ["ars"],
                 "AMD": ["amd"],
                 "AWG": ["awg"],
                 "SHP": ["shp"],
                 "AUD": ["aud"],
                 "AZN": ["azn"],
                 "BSD": ["bsd"],
                 "BHD": ["bhd"],
                 "BDT": ["bdt"],
                 "BBD": ["bbd"],
                 "BYN": ["byn"],
                 "BZD": ["bzd"],
                 "XOF": ["xof"],
                 "BMD": ["bmd"],
                 "BTN": ["btn"],
                 "BOB": ["bob"],
                 "BAM": ["bam"],
                 "BWP": ["bwp"],
                 "BRL": ["brl"],
                 "BND": ["bnd"],
                 "BGN": ["bgn"],
                 "BIF": ["bif"],
                 "CVE": ["cve"],
                 "KHR": ["KHR"],
                 "XAF": ["xaf"],
                 "CAD": ["cad"],
                 "KYD": ["kyd"],
                 "NZD": ["nzd"],
                 "CLP": ["clp"],
                 "CNY": ["cny"],
                 "COP": ["cop"],
                 "KMF": ["kmf"],
                 "CDF": ["cdf"],
                 "none": ["none"],
                 "CRC": ["crc"],
                 "HRK": ["hrk"],
                 "CUP": ["cup"],
                 "ANG": ["ang"],
                 "CZK": ["czk"],
                 "DKK": ["dkk"],
                 "DJF": ["djf"],
                 "DOP": ["dop"],
                 "EGP": ["egp"],
                 "ERN": ["ern"],
                 "ETB": ["etb"],
                 "FKP": ["fkp"],
                 "FJD": ["fjd"],
                 "XPF": ["xpf"],
                 "GMD": ["gmd"],
                 "GEL": ["gel"],
                 "GHS": ["ghs"],
                 "GIP": ["gip"],
                 "GTQ": ["gtq"],
                 "GGP": ["ggp"],
                 "GNF": ["gnf"],
                 "GYD": ["gyd"],
                 "HTG": ["htg"],
                 "HNL": ["hnl"],
                 "HKD": ["hkd"],
                 "HUF": ["huf"],
                 "ISK": ["isk"],
                 "INR": ["inr"],
                 "IDR": ["idr"],
                 "XDR": ["xdr"],
                 "IRR": ["irr"],
                 "IQD": ["iqd"],
                 "IMP": ["imp"],
                 "ILS": ["ils"],
                 "JMD": ["jmd"],
                 "JPY": ["jpy"],
                 "JEP": ["jep"],
                 "JOD": ["jod"],
                 "KZT": ["kzt"],
                 "KES": ["kes"],
                 "KWD": ["kwd"],
                 "KGS": ["kgs"],
                 "LAK": ["lak"],
                 "LBP": ["lbp"],
                 "LSL": ["lsl"],
                 "LRD": ["lrd"],
                 "LYD": ["lyd"],
                 "CHF": ["chf"],
                 "MOP": ["mop"],
                 "MKD": ["mkd"],
                 "MGA": ["mga"],
                 "MWK": ["mwk"],
                 "MYR": ["myr"],
                 "MVR": ["mvr"],
                 "MRO": ["mro"],
                 "MUR": ["mur"],
                 "MXN": ["mxn"],
                 "MDL": ["mdl"],
                 "MNT": ["mnt"],
                 "MAD": ["mad"],
                 "MZN": ["mzn"],
                 "MMK": ["mmk"],
                 "NAD": ["nad"],
                 "NPR": ["npr"],
                 "NIO": ["nio"],
                 "KPW": ["kpw"],
                 "NOK": ["nok"],
                 "OMR": ["omr"],
                 "PKR": ["pkr"],
                 "PGK": ["pgk"],
                 "PYG": ["pyg"],
                 "PEN": ["pen"],
                 "PHP": ["php"],
                 "PLN": ["pln"],
                 "QAR": ["qar"],
                 "RON": ["ron"],
                 "RUB": ["rub"],
                 "RWF": ["rwf"],
                 "WST": ["wst"],
                 "STD": ["std"],
                 "SAR": ["sar"],
                 "RSD": ["rsd"],
                 "SCR": ["scr"],
                 "SLL": ["sll"],
                 "SGD": ["sgd"],
                 "SBD": ["sbd"],
                 "SOS": ["sos"],
                 "ZAR": ["zar"],
                 "GBP": ["pounds", "pound","gbp"],
                 "KRW": ["krw"],
                 "SSP": ["ssp"],
                 "LKR": ["lkr"],
                 "SDG": ["sdg"],
                 "SRD": ["srd"],
                 "SZL": ["szl"],
                 "SEK": ["sek"],
                 "SYP": ["syp"],
                 "TWD": ["twd"],
                 "TJS": ["tjs"],
                 "TZS": ["tzs"],
                 "THB": ["thb"],
                 "TOP": ["top"],
                 "TTD": ["ttd"],
                 "TND": ["tnd"],
                 "TRY": ["try"],
                 "TMT": ["tmt"],
                 "UGX": ["ugx"],
                 "UAH": ["uah"],
                 "AED": ["aed"],
                 "UYU": ["uyu"],
                 "UZS": ["uzs"],
                 "VUV": ["vuv"],
                 "VEF": ["vef"],
                 "VND": ["vnd"],
                 "YER": ["yer"],
                 "ZMW": ["zmw"]}

                
AccountStatus_dict = {
    '001': ['001', 'open','opened', '01', '1', 'active'],
    '002': ['002', 'closed', '02', '2'],
    '003': ['003', 'written off', 'written0ff','writtenoff', '03', '3','write off']
}

ConsuToComm={
    # 'DATA':['DATA'],
    'BUSINESSREGISTRATIONNUMBER':[''],
    'BUSINESSNAME':['SURNAME'],
    'BUSINESSTRADINGNAME':[''],
    'BUSINESSCATEGORY':[''],
    'BUSINESSSECTOR':[''],
    'DATEOFINCORPORATION':['DATEOFBIRTH'],
    'CUSTOMERID':['CUSTOMERID'],
    'CUSTOMERBRANCHCODE':['BRANCHCODE'],
    'BUSINESSOFFICEADDRESSLINE1':['PRIMARYADDRESSLINE1'],
    'BUSINESSOFFICEADDRESSLINE2':['PRIMARYADDRESSLINE2'],
    'BUSINESSOFFICEADDRESSCITYLGA':['PRIMARYADDRESSCITY'],
    'BUSINESSOFFICEADDRESSSTATE':['PRIMARYADDRESSSTATE'],
    'BUSINESSOFFICEADDRESSCOUNTRY':['PRIMARYADDRESSCOUNTRY'],
    'BUSINESSOFFICEADDRESSPOSTCODE':['PRIMARYADDRESSPOSTCODE'],
    'EMAILADDRESS':['EMAILADDRESS'],
    'SECONDARYADDRESSLINE1':['SECONDARYADDRESSLINE1'],
    'SECONDARYADDRESSLINE2':['SECONDARYADDRESSLINE2'],
    'SECONDARYADDRESSCITYLGA':['SECONDARYADDRESSCITYLGA'],
    'SECONDARYADDRESSSTATE':['SECONDARYADDRESSSTATE'],
    'SECONDARYADDRESSCOUNTRY':['SECONDARYADDRESSCOUNTRY'],
    'SECONDARYADDRESSPOSTCODE':[''],
    'TAXID':[''],
    'PRIMARYPHONENUMBER':['MOBILENUMBER'],
    'SECONDARYPHONENUMBER':['WORKTELEPHONE'],
    'ACCOUNTNUMBER':['ACCOUNTNUMBER'],
    'ACCOUNTSTATUS':['ACCOUNTSTATUS'],
    'ACCOUNTSTATUSDATE':['ACCOUNTSTATUSDATE'],
    'LOANEFFECTIVEDATE':['LOANEFFECTIVEDATE'],
    'DEFEREDPAYMENTDATE':['DEFEREDPAYMENTDATE'],
    'CREDITLIMIT':['CREDITLIMIT'],
    'AVAILEDLIMIT':['AVAILEDLIMIT'],
    'OUTSTANDINGBALANCE':['OUTSTANDINGBALANCE'],
    'CURRENTBALANCEDEBITIND':['CURRENTBALANCEDEBITIND'],
    'INSTALMENTAMOUNT':['INSTALMENTAMOUNT'],
    'CURRENCY':['CURRENCY'],
    'DAYSINARREARS':['DAYSINARREARS'],
    'OVERDUEAMOUNT':['OVERDUEAMOUNT'],
    'FACILITYTYPE':['FACILITYTYPE'],
    'FACILITYTENOR':['FACILITYTENOR'],
    'REPAYMENTFREQUENCY':['REPAYMENTFREQUENCY'],
    'LASTPAYMENTDATE':['LASTPAYMENTDATE'],
    'LASTPAYMENTAMOUNT':['LASTPAYMENTAMOUNT'],
    'MATURITYDATE':['MATURITYDATE'],
    'LOANCLASSIFICATION':['LOANCLASSIFICATION'],
    'LEGALCHALLENGESTATUS':['LEGALCHALLENGESTATUS'],
    'LITIGATIONDATE':['LITIGATIONDATE'],
    'CONSENTSTATUS':['CONSENTSTATUS'],
    'LOANSECURITYSTATUS':['LOANSECURITYSTATUS'],
    'COLLATERALTYPE':['COLLATERALTYPE'],
    'COLLATERALDETAILS':['COLLATERALDETAILS'],
    'PREVIOUSACCOUNTNUMBER':['PREVIOUSACCOUNTNUMBER'],
    'PREVIOUSNAME':['PREVIOUSNAME'],
    'PREVIOUSCUSTOMERID':['PREVIOUSCUSTOMERID'],
    'PREVIOUSBRANCHCODE':['PREVIOUSBRANCHCODE'],

    'PRINCIPALOFFICER1SURNAME':['INDIVIDUALGUARANTORSURNAME'],
    'PRINCIPALOFFICER1FIRSTNAME':['INDIVIDUALGUARANTORFIRSTNAME'],
    'PRINCIPALOFFICER1MIDDLENAME':['INDIVIDUALGUARNTORMIDDLENAME'],
    'PRINCIPALOFFICER1DATEOFBIRTH':['GUARANTORDATEOFBIRTHINCORPORATION'],
    'PRINCIPALOFFICER1GENDER':['GUARANTORGENDER'],
    'PRINCIPALOFFICER1PRIMARYADDRESSLINE1':['GUARANTORPRIMARYADDRESSLINE1'],
    'PRINCIPALOFFICER1PRIMARYADDRESSLINE2':['GUARANTORPRIMARYADDRESSLINE2'],
    'PRINCIPALOFFICER1CITY':['GUARANTORPRIMARYADDRESSCITYLGA'],
    'PRINCIPALOFFICER1STATE':['GUARANTORPRIMARYADDRESSSTATE'],
    'PRINCIPALOFFICER1COUNTRY':['GUARANTORPRIMARYADDRESSCOUNTRY'],
    'PRINCIPALOFFICER1NATIONALID':[''],
    'PRINCIPALOFFICER1DRIVERSLICENSENUMBER':[''],
    'PRINCIPALOFFICER1BVNNUMBER':[''],
    'PRINCIPALOFFICER1PASSPORTNUMBER':[''],
    'PRINCIPALOFFICER1OTHERIDNUMBER':[''],
    'PRINCIPALOFFICER1PHONENUMBER':['GUARANTORPRIMARYPHONENUMBER'],
    'PRINCIPALOFFICER1EMAILADDRESS':[''],
    'PRINCIPALOFFICER1POSITIONINBUSINESS':[''],
    'PRINCIPALOFFICER2SURNAME':[''],
    'PRINCIPALOFFICER2FIRSTNAME':[''],
    'PRINCIPALOFFICER2MIDDLENAME':[''],
    'PRINCIPALOFFICER2DATEOFBIRTH':[''],
    'PRINCIPALOFFICER2GENDER':[''],
    'PRINCIPALOFFICER2PRIMARYADDRESSLINE1':[''],
    'PRINCIPALOFFICER2PRIMARYADDRESSLINE2':[''],
    'PRINCIPALOFFICER2CITY':[''],
    'PRINCIPALOFFICER2STATE':[''],
    'PRINCIPALOFFICER2COUNTRY':[''],
    'PRINCIPALOFFICER2NATIONALID':[''],
    'PRINCIPALOFFICER2DRIVERSLISCENCENUMBER':[''],
    'PRINCIPALOFFICER2BVNNUMBER':[''],
    'PRINCIPALOFFICER2PASSPORTNUMBER':[''],
    'PRINCIPALOFFICER2OTHERIDNUMBER':[''],    
    'PRINCIPALOFFICER2PHONENUMBER':[''],
    'PRINCIPALOFFICER2EMAILADDRESS':[''],
    'PRINCIPALOFFICER2POSITIONINBUSINESS':['']}


Loan_dict = {'001': ['commercialoverdraft', '1', '01', '001', 'CommercialOverdraft'],
                '002': ['commercialcreditcardloan', '2', '02', '002', 'CommercialCreditCardLoan'],
                '003': ['commercialrevolvingrenewableshorttermcredit', '3', '03', '003', 'CommercialRevolvingCredit'],
                '004': ['commercialmortgageloanincludingmortgagerefinancing', '4', '04', '004'],
                '005': ['commercialrentfacility', '5', '05', '005'],
                '006': ['commerciallandpurchasefinancing', '6', '06', '006'],
                '007': ['commercialbusinessautoloan', 'commercialautoloan', 'businessautoloan', '7', '07', '007'],
                '008': ['commercialbusinessequipmentassetleasingfinancing', 'businessequipmentasset', '8', '08', '008'],
                '009': ['commercialbusinessfixedtermloan', 'commercialfixedtermloan', 'businessfixedtermloan', '9', '09', '009'],
                '010': ['foreigndenominatedcommercialloan', '10', '010'],
                '011': ['commercialinvestmentloan', '11', '011'],
                '012': ['localpurchaseorderlposupplycontractfinancing', 'localpurchaseorder', 'supplycontractfinancing', 'lpo', '12', '012'],
                '013': ['distributorsuppliercreditfinance', '13', '013'],
                '014': ['invoicediscountingaccountreceivablewarehousereceiptfinance', 'invoicediscounting', 'accountreceivable', 'warehousereceiptfinance', '14', '014'],
                '015': ['oilandgascontractfinance', 'oilgas', 'oilcontractfinance', 'gascontractfinance', 'oilgascontractfinance', '15', '015'],
                '016': ['projectfinancinglongterminfrastructureindustrialpublicservicefinancenonrecoursedebtnonrecoursefinance', '16', '016', 'projectfinancing', 'longterminfrastructure', 'industrial', 'publicservicefinance', 'nonrecoursedebt', 'nonrecoursefinance'],
                '017': ['buildoperatetransferfinance', 'botcontract', 'bottransfer', 'buildoperatetransfercontract', 'buildoperatetransferbotcontractfinance', '17', '017'],
                '018': ["Bankersacceptancefacility", "Bankeracceptancefacility", '18', '018'],
                '019': ['commercialpaper', '19', '019'],
                '020': ['internationaltradefinanceletterofcredit', 'internationaltradefinance', 'letterofcredit', '20', '020'],
                '021': ['importfinance', 'importfinancestockreplacementfacility', 'stockreplacementfacility', '21', '021'],
                '022': ['exportfinance', '22', '022'],
                '023': ['bondandguaranteesbidbondscustomsexcisebondsadvancepaymentguaranteeperformancebondsetc', '23', '023', 'bondandguarantees', 'bidbonds', 'bidbond', 'customsexcisebonds', 'customsexcisebond', 'advancepaymentguarantee', 'performancebonds', 'performancebond'],
                '024': ['loansyndication', 'loansyndicationcompetitivebidoption', 'competitivebidoption', '24', '024'],
                '025': ['businesstravelloan', '25', '025'],
                '026': ['businessagriculturefinance', '26', '026'],
                '027': ['treasurybills', 'treasurybill', '27', '027'],
                '028': ['governmentbackedloan', '28', '028'],
                '029': ['Microfinanceorsmallproprietorloan', 'Microfinanceproprietorloan', 'smallproprietorloan', '29', '029'],
                '030': ['personaloverdraft', '30', '030'],
                '031': ['personalcreditcardloan', '31', '031'],
                '032': ['personalrevolvingrenewableshorttermcredit', '32', '032'],
                '033': ['personalsecuredloan', '33', '033'],
                '034': ['personalhomemortgageincludingmortgagerefinance', 'mortgagerefinance', 'personalhomemortgage', '34', '034'],
                '035': ['residentialrentfacility', '35', '035'],
                '036': ['personallandpurchasefinancing', 'landpurchase', '36', '036'],
                '037': ['nationalhousingfundloan', '37', '037'],
                '038': ['personalautoloan', '38', '038'],
                '039': ['personalconsumerequipmentassethirepurchaseleasingfinancing', 'consumerequipment', 'assethirepurchase', '39', '039'],
                '040': ['Personalfixedtermloan', '40', '040'],
                '041': ['paydayloanorsalaryadvance', 'paydayloan', 'salaryadvance', '41', '041'],
                '042': ['personalbulletoronetimeloanpayment', 'onetimeloanpayment', 'personalbullet', '42', '042'],
                '043': ['foreigndenominatedpersonalloan', 'foreignpersonalloan', '43', '043'],
                '044': ['personalinvestmentloan', '44', '044'],
                '045': ['educationorstudentloan', 'educationloan', 'studentloan', '45', '045'],
                '046': ['sharesacquisitionpurchaseormarginloan', 'purchaseormarginloan', 'sharesacquisition', '46', '046'],
                '047': ['personaltravelorvacationloan', 'personaltravel', 'vacationloan', '47', '047'],
                '048': ['personalagriculturefinance', '48', '048'],
                '049': ['darahoperatinglease', '49', '049'],
                '050': ['ijarahwaigtinafinancelease', '50', '050'],
                '051': ['mudarabatrusteepartnership', '51', '051'],
                '052': ['nusharauamusharakahequitypartnership', 'nusharauaequitypartnership', 'musharakahequitypartnership', '52', '052'],
                '053': ['istinamanufacturingproductionfinance', 'productionfinance', 'istinamanufacturing', '53', '053'],
                '054': ['Salamadvancepaymentforagricfinance', 'advancepaymentforagricfinance', '54', '054'],
                '055': ['commoditymuraba', '55', '055'],
                '056': ['wakakagency', '56', '056'],
                '057': ['qardhassanbenevoltloan', 'benevoltloan', 'qardhassan', '57', '057'],
                '058': ['baimuajjaldeferredsalecreditsale', 'creditsale', 'baimuajjaldeferredsale', '58', '058'],
                '059': ['sukur', '59', '059'],
                '060': ['istijrarcontinoussale', '60', '060'],
                '061': ['murabahamarkupsale', '61', '061'],
                '062': ['baiassarfforeignexchangefxtrade', 'baiassarfforeignexchange', 'fxtrade', '62', '062'],
                '063': ['wakalaagencyguarantee', '63', '063'],
                '064': ['kafalaguarantee', '64', '064']
                 }

Repayment_dict = {'1':['d','w','1','days','day','weekly','daily','01','001','day','week'],
                  '2':['f','2','forthnight','02','002','forth','forthnightly'],
                  '3':['m','month','monthly', '3','03','003'],
                  '4':['q','quarter','quarterly','4','04','004'],
                  '5':['5','sixmonth','sixmonths','6months','6month','halfyear','half year','05','005'],
                  '6': ['y','yearly','year','6','06','006','one year','1year'],
                  '7':['b','bullet', '7','07','007']
}
Classification_dict = {'001':['001', 'performing','1','01','perform',"performingloans","performingadvances", "performing loans","performing advances"],
                       '002':['002','watchlist','02','2',"pass and watch"],
                       '003':['003','sub standard','substandard','03','3','sub'],
                       '004':['004', 'doubtful','04','4'],
                       '005':['005','lost','05','5']
}
Collateraltype_dict = {
                      '001':['001','realestatelandbuilding','01','1','realestate','land','building'],
                      '002':['002','Automobile','02','2'],
                      '003':['003','plantequipment','plantandequipment','equipment','plant','03','3'],
                      '004':['004','naturalreserves','natural','reserves','04','4'],
                      '005':['005','marketablesecurities','marketable','securities','05','5'],
                      '006':['006','accountsreceivablesandinventory','accountsreceivable','accountsreceivables','inventory','accountsreceivablesinventory','06','6'],
                      '007':['007','cash','07','7'],
                      '008':['008','personalguarantees','personalguarantee','personal','guarantees','08','8'],
                      '009':['009','postdatedcheques','postcheques','datedcheques','cheques','09','9'],
                      '010':['010','dormicilliation','10']
                      }

